package com.iawtr.database.dto;
// Generated 2019-1-7 14:12:28 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * DjCf generated by hbm2java
 */
public class DjCf  implements java.io.Serializable ,DtoInterface {
	private static final long serialVersionUID = 1L;

     private String slbh;
     private String cfbh;
     private String xgzh;
     private String bdcdyh;
     private BigDecimal cfsx;
     private String cfjg;
     private String cflx;
     private String cfwj;
     private String cfwh;
     private Date cfqssj;
     private Date cfjssj;
     private String cffw;
     private BigDecimal cfbdcdy;
     private String djjg;
     private String dbr;
     private Date djsj;
     private String cfyy;
     private String jbr;
     private Date jbrq;
     private String gdh;
     private String damj;
     private String qt;
     private String fj;
     private String qlr;
     private String zjbh;
     private Date lwrq;
     private String lhxx;
     private BigDecimal lifecycle;
     private String ygr;
     private String cfqx;
     private String spbz;
     private String wz;
     private String houseid;
     private String regid;
     private String gmr;

    public DjCf() {
    }

	
    public DjCf(String slbh) {
        this.slbh = slbh;
    }
    public DjCf(String slbh, String cfbh, String xgzh, String bdcdyh, BigDecimal cfsx, String cfjg, String cflx, String cfwj, String cfwh, Date cfqssj, Date cfjssj, String cffw, BigDecimal cfbdcdy, String djjg, String dbr, Date djsj, String cfyy, String jbr, Date jbrq, String gdh, String damj, String qt, String fj, String qlr, String zjbh, Date lwrq, String lhxx, BigDecimal lifecycle, String ygr, String cfqx, String spbz, String wz, String houseid, String regid, String gmr) {
       this.slbh = slbh;
       this.cfbh = cfbh;
       this.xgzh = xgzh;
       this.bdcdyh = bdcdyh;
       this.cfsx = cfsx;
       this.cfjg = cfjg;
       this.cflx = cflx;
       this.cfwj = cfwj;
       this.cfwh = cfwh;
       this.cfqssj = cfqssj;
       this.cfjssj = cfjssj;
       this.cffw = cffw;
       this.cfbdcdy = cfbdcdy;
       this.djjg = djjg;
       this.dbr = dbr;
       this.djsj = djsj;
       this.cfyy = cfyy;
       this.jbr = jbr;
       this.jbrq = jbrq;
       this.gdh = gdh;
       this.damj = damj;
       this.qt = qt;
       this.fj = fj;
       this.qlr = qlr;
       this.zjbh = zjbh;
       this.lwrq = lwrq;
       this.lhxx = lhxx;
       this.lifecycle = lifecycle;
       this.ygr = ygr;
       this.cfqx = cfqx;
       this.spbz = spbz;
       this.wz = wz;
       this.houseid = houseid;
       this.regid = regid;
       this.gmr = gmr;
    }
   
    public String getSlbh() {
        return this.slbh;
    }
    
    public void setSlbh(String slbh) {
        this.slbh = slbh;
    }
    public String getCfbh() {
        return this.cfbh;
    }
    
    public void setCfbh(String cfbh) {
        this.cfbh = cfbh;
    }
    public String getXgzh() {
        return this.xgzh;
    }
    
    public void setXgzh(String xgzh) {
        this.xgzh = xgzh;
    }
    public String getBdcdyh() {
        return this.bdcdyh;
    }
    
    public void setBdcdyh(String bdcdyh) {
        this.bdcdyh = bdcdyh;
    }
    public BigDecimal getCfsx() {
        return this.cfsx;
    }
    
    public void setCfsx(BigDecimal cfsx) {
        this.cfsx = cfsx;
    }
    public String getCfjg() {
        return this.cfjg;
    }
    
    public void setCfjg(String cfjg) {
        this.cfjg = cfjg;
    }
    public String getCflx() {
        return this.cflx;
    }
    
    public void setCflx(String cflx) {
        this.cflx = cflx;
    }
    public String getCfwj() {
        return this.cfwj;
    }
    
    public void setCfwj(String cfwj) {
        this.cfwj = cfwj;
    }
    public String getCfwh() {
        return this.cfwh;
    }
    
    public void setCfwh(String cfwh) {
        this.cfwh = cfwh;
    }
    public Date getCfqssj() {
        return this.cfqssj;
    }
    
    public void setCfqssj(Date cfqssj) {
        this.cfqssj = cfqssj;
    }
    public Date getCfjssj() {
        return this.cfjssj;
    }
    
    public void setCfjssj(Date cfjssj) {
        this.cfjssj = cfjssj;
    }
    public String getCffw() {
        return this.cffw;
    }
    
    public void setCffw(String cffw) {
        this.cffw = cffw;
    }
    public BigDecimal getCfbdcdy() {
        return this.cfbdcdy;
    }
    
    public void setCfbdcdy(BigDecimal cfbdcdy) {
        this.cfbdcdy = cfbdcdy;
    }
    public String getDjjg() {
        return this.djjg;
    }
    
    public void setDjjg(String djjg) {
        this.djjg = djjg;
    }
    public String getDbr() {
        return this.dbr;
    }
    
    public void setDbr(String dbr) {
        this.dbr = dbr;
    }
    public Date getDjsj() {
        return this.djsj;
    }
    
    public void setDjsj(Date djsj) {
        this.djsj = djsj;
    }
    public String getCfyy() {
        return this.cfyy;
    }
    
    public void setCfyy(String cfyy) {
        this.cfyy = cfyy;
    }
    public String getJbr() {
        return this.jbr;
    }
    
    public void setJbr(String jbr) {
        this.jbr = jbr;
    }
    public Date getJbrq() {
        return this.jbrq;
    }
    
    public void setJbrq(Date jbrq) {
        this.jbrq = jbrq;
    }
    public String getGdh() {
        return this.gdh;
    }
    
    public void setGdh(String gdh) {
        this.gdh = gdh;
    }
    public String getDamj() {
        return this.damj;
    }
    
    public void setDamj(String damj) {
        this.damj = damj;
    }
    public String getQt() {
        return this.qt;
    }
    
    public void setQt(String qt) {
        this.qt = qt;
    }
    public String getFj() {
        return this.fj;
    }
    
    public void setFj(String fj) {
        this.fj = fj;
    }
    public String getQlr() {
        return this.qlr;
    }
    
    public void setQlr(String qlr) {
        this.qlr = qlr;
    }
    public String getZjbh() {
        return this.zjbh;
    }
    
    public void setZjbh(String zjbh) {
        this.zjbh = zjbh;
    }
    public Date getLwrq() {
        return this.lwrq;
    }
    
    public void setLwrq(Date lwrq) {
        this.lwrq = lwrq;
    }
    public String getLhxx() {
        return this.lhxx;
    }
    
    public void setLhxx(String lhxx) {
        this.lhxx = lhxx;
    }
    public BigDecimal getLifecycle() {
        return this.lifecycle;
    }
    
    public void setLifecycle(BigDecimal lifecycle) {
        this.lifecycle = lifecycle;
    }
    public String getYgr() {
        return this.ygr;
    }
    
    public void setYgr(String ygr) {
        this.ygr = ygr;
    }
    public String getCfqx() {
        return this.cfqx;
    }
    
    public void setCfqx(String cfqx) {
        this.cfqx = cfqx;
    }
    public String getSpbz() {
        return this.spbz;
    }
    
    public void setSpbz(String spbz) {
        this.spbz = spbz;
    }
    public String getWz() {
        return this.wz;
    }
    
    public void setWz(String wz) {
        this.wz = wz;
    }
    public String getHouseid() {
        return this.houseid;
    }
    
    public void setHouseid(String houseid) {
        this.houseid = houseid;
    }
    public String getRegid() {
        return this.regid;
    }
    
    public void setRegid(String regid) {
        this.regid = regid;
    }
    public String getGmr() {
        return this.gmr;
    }
    
    public void setGmr(String gmr) {
        this.gmr = gmr;
    }


	@Override
	public String getIdName() {
		// TODO Auto-generated method stub
		return "slbh";
	}


	@Override
	public String getDataVersionName() {
		// TODO Auto-generated method stub
		return null;
	}




}


