package com.iawtr.database.dto;
// Generated 2019-1-7 14:12:28 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * DjDjb generated by hbm2java
 */
public class DjDjb  implements java.io.Serializable ,DtoInterface {
	private static final long serialVersionUID = 1L;

     private String slbh;
     private String djlx;
     private String djyy;
     private String sqzsbs;
     private String sqfbcz;
     private Date sqrq;
     private String sqnr;
     private String sqbz;
     private String dljgmc;
     private String dlrxm;
     private String dlrzjlx;
     private String dlrzjh;
     private String dlrzgzh;
     private String dlrdh;
     private String dljgmc2;
     private String dlrxm2;
     private String dlrzjlx2;
     private String dlrzjh2;
     private String dlrzgzh2;
     private String dlrdh2;
     private String spdw;
     private Date sprq;
     private String spbz;
     private String bdczh;
     private String ssjc;
     private String jgjc;
     private String fznd;
     private String zsh;
     private String szr;
     private String gyfs;
     private String gyfe;
     private Date djrq;
     private String dbr;
     private String zsr;
     private String fzjg;
     private Date fzrq;
     private String zslx;
     private String zsxlh;
     private BigDecimal dycs;
     private String gdh;
     private String damj;
     private String qt;
     private String fj;
     private String xgzh;
     private String glzh;
     private String bdcdyh;
     private String hdpch;
     private String szpch;
     private String zxdjdybh;
     private BigDecimal lifecycle;
     private String appid;
     private String yslbh;
     private BigDecimal lifecycle1;
     private String zl;
     private String djyy1;
     private String bdczhtemp;
     private String bdczh1;
     private BigDecimal sfcz;
     private BigDecimal fccz;
     private BigDecimal sfcf;
     private String yfj;
     private BigDecimal lifecycle2;
     private String wz;
     private String dzzsxlh;
     private String bdczh2;
     private String regid;
     private BigDecimal snum;
     private String qtfj;
     private String zjsm;

    public DjDjb() {
    }

	
    public DjDjb(String slbh) {
        this.slbh = slbh;
    }
    public DjDjb(String slbh, String djlx, String djyy, String sqzsbs, String sqfbcz, Date sqrq, String sqnr, String sqbz, String dljgmc, String dlrxm, String dlrzjlx, String dlrzjh, String dlrzgzh, String dlrdh, String dljgmc2, String dlrxm2, String dlrzjlx2, String dlrzjh2, String dlrzgzh2, String dlrdh2, String spdw, Date sprq, String spbz, String bdczh, String ssjc, String jgjc, String fznd, String zsh, String szr, String gyfs, String gyfe, Date djrq, String dbr, String zsr, String fzjg, Date fzrq, String zslx, String zsxlh, BigDecimal dycs, String gdh, String damj, String qt, String fj, String xgzh, String glzh, String bdcdyh, String hdpch, String szpch, String zxdjdybh, BigDecimal lifecycle, String appid, String yslbh, BigDecimal lifecycle1, String zl, String djyy1, String bdczhtemp, String bdczh1, BigDecimal sfcz, BigDecimal fccz, BigDecimal sfcf, String yfj, BigDecimal lifecycle2, String wz, String dzzsxlh, String bdczh2, String regid, BigDecimal snum, String qtfj, String zjsm) {
       this.slbh = slbh;
       this.djlx = djlx;
       this.djyy = djyy;
       this.sqzsbs = sqzsbs;
       this.sqfbcz = sqfbcz;
       this.sqrq = sqrq;
       this.sqnr = sqnr;
       this.sqbz = sqbz;
       this.dljgmc = dljgmc;
       this.dlrxm = dlrxm;
       this.dlrzjlx = dlrzjlx;
       this.dlrzjh = dlrzjh;
       this.dlrzgzh = dlrzgzh;
       this.dlrdh = dlrdh;
       this.dljgmc2 = dljgmc2;
       this.dlrxm2 = dlrxm2;
       this.dlrzjlx2 = dlrzjlx2;
       this.dlrzjh2 = dlrzjh2;
       this.dlrzgzh2 = dlrzgzh2;
       this.dlrdh2 = dlrdh2;
       this.spdw = spdw;
       this.sprq = sprq;
       this.spbz = spbz;
       this.bdczh = bdczh;
       this.ssjc = ssjc;
       this.jgjc = jgjc;
       this.fznd = fznd;
       this.zsh = zsh;
       this.szr = szr;
       this.gyfs = gyfs;
       this.gyfe = gyfe;
       this.djrq = djrq;
       this.dbr = dbr;
       this.zsr = zsr;
       this.fzjg = fzjg;
       this.fzrq = fzrq;
       this.zslx = zslx;
       this.zsxlh = zsxlh;
       this.dycs = dycs;
       this.gdh = gdh;
       this.damj = damj;
       this.qt = qt;
       this.fj = fj;
       this.xgzh = xgzh;
       this.glzh = glzh;
       this.bdcdyh = bdcdyh;
       this.hdpch = hdpch;
       this.szpch = szpch;
       this.zxdjdybh = zxdjdybh;
       this.lifecycle = lifecycle;
       this.appid = appid;
       this.yslbh = yslbh;
       this.lifecycle1 = lifecycle1;
       this.zl = zl;
       this.djyy1 = djyy1;
       this.bdczhtemp = bdczhtemp;
       this.bdczh1 = bdczh1;
       this.sfcz = sfcz;
       this.fccz = fccz;
       this.sfcf = sfcf;
       this.yfj = yfj;
       this.lifecycle2 = lifecycle2;
       this.wz = wz;
       this.dzzsxlh = dzzsxlh;
       this.bdczh2 = bdczh2;
       this.regid = regid;
       this.snum = snum;
       this.qtfj = qtfj;
       this.zjsm = zjsm;
    }
   
    public String getSlbh() {
        return this.slbh;
    }
    
    public void setSlbh(String slbh) {
        this.slbh = slbh;
    }
    public String getDjlx() {
        return this.djlx;
    }
    
    public void setDjlx(String djlx) {
        this.djlx = djlx;
    }
    public String getDjyy() {
        return this.djyy;
    }
    
    public void setDjyy(String djyy) {
        this.djyy = djyy;
    }
    public String getSqzsbs() {
        return this.sqzsbs;
    }
    
    public void setSqzsbs(String sqzsbs) {
        this.sqzsbs = sqzsbs;
    }
    public String getSqfbcz() {
        return this.sqfbcz;
    }
    
    public void setSqfbcz(String sqfbcz) {
        this.sqfbcz = sqfbcz;
    }
    public Date getSqrq() {
        return this.sqrq;
    }
    
    public void setSqrq(Date sqrq) {
        this.sqrq = sqrq;
    }
    public String getSqnr() {
        return this.sqnr;
    }
    
    public void setSqnr(String sqnr) {
        this.sqnr = sqnr;
    }
    public String getSqbz() {
        return this.sqbz;
    }
    
    public void setSqbz(String sqbz) {
        this.sqbz = sqbz;
    }
    public String getDljgmc() {
        return this.dljgmc;
    }
    
    public void setDljgmc(String dljgmc) {
        this.dljgmc = dljgmc;
    }
    public String getDlrxm() {
        return this.dlrxm;
    }
    
    public void setDlrxm(String dlrxm) {
        this.dlrxm = dlrxm;
    }
    public String getDlrzjlx() {
        return this.dlrzjlx;
    }
    
    public void setDlrzjlx(String dlrzjlx) {
        this.dlrzjlx = dlrzjlx;
    }
    public String getDlrzjh() {
        return this.dlrzjh;
    }
    
    public void setDlrzjh(String dlrzjh) {
        this.dlrzjh = dlrzjh;
    }
    public String getDlrzgzh() {
        return this.dlrzgzh;
    }
    
    public void setDlrzgzh(String dlrzgzh) {
        this.dlrzgzh = dlrzgzh;
    }
    public String getDlrdh() {
        return this.dlrdh;
    }
    
    public void setDlrdh(String dlrdh) {
        this.dlrdh = dlrdh;
    }
    public String getDljgmc2() {
        return this.dljgmc2;
    }
    
    public void setDljgmc2(String dljgmc2) {
        this.dljgmc2 = dljgmc2;
    }
    public String getDlrxm2() {
        return this.dlrxm2;
    }
    
    public void setDlrxm2(String dlrxm2) {
        this.dlrxm2 = dlrxm2;
    }
    public String getDlrzjlx2() {
        return this.dlrzjlx2;
    }
    
    public void setDlrzjlx2(String dlrzjlx2) {
        this.dlrzjlx2 = dlrzjlx2;
    }
    public String getDlrzjh2() {
        return this.dlrzjh2;
    }
    
    public void setDlrzjh2(String dlrzjh2) {
        this.dlrzjh2 = dlrzjh2;
    }
    public String getDlrzgzh2() {
        return this.dlrzgzh2;
    }
    
    public void setDlrzgzh2(String dlrzgzh2) {
        this.dlrzgzh2 = dlrzgzh2;
    }
    public String getDlrdh2() {
        return this.dlrdh2;
    }
    
    public void setDlrdh2(String dlrdh2) {
        this.dlrdh2 = dlrdh2;
    }
    public String getSpdw() {
        return this.spdw;
    }
    
    public void setSpdw(String spdw) {
        this.spdw = spdw;
    }
    public Date getSprq() {
        return this.sprq;
    }
    
    public void setSprq(Date sprq) {
        this.sprq = sprq;
    }
    public String getSpbz() {
        return this.spbz;
    }
    
    public void setSpbz(String spbz) {
        this.spbz = spbz;
    }
    public String getBdczh() {
        return this.bdczh;
    }
    
    public void setBdczh(String bdczh) {
        this.bdczh = bdczh;
    }
    public String getSsjc() {
        return this.ssjc;
    }
    
    public void setSsjc(String ssjc) {
        this.ssjc = ssjc;
    }
    public String getJgjc() {
        return this.jgjc;
    }
    
    public void setJgjc(String jgjc) {
        this.jgjc = jgjc;
    }
    public String getFznd() {
        return this.fznd;
    }
    
    public void setFznd(String fznd) {
        this.fznd = fznd;
    }
    public String getZsh() {
        return this.zsh;
    }
    
    public void setZsh(String zsh) {
        this.zsh = zsh;
    }
    public String getSzr() {
        return this.szr;
    }
    
    public void setSzr(String szr) {
        this.szr = szr;
    }
    public String getGyfs() {
        return this.gyfs;
    }
    
    public void setGyfs(String gyfs) {
        this.gyfs = gyfs;
    }
    public String getGyfe() {
        return this.gyfe;
    }
    
    public void setGyfe(String gyfe) {
        this.gyfe = gyfe;
    }
    public Date getDjrq() {
        return this.djrq;
    }
    
    public void setDjrq(Date djrq) {
        this.djrq = djrq;
    }
    public String getDbr() {
        return this.dbr;
    }
    
    public void setDbr(String dbr) {
        this.dbr = dbr;
    }
    public String getZsr() {
        return this.zsr;
    }
    
    public void setZsr(String zsr) {
        this.zsr = zsr;
    }
    public String getFzjg() {
        return this.fzjg;
    }
    
    public void setFzjg(String fzjg) {
        this.fzjg = fzjg;
    }
    public Date getFzrq() {
        return this.fzrq;
    }
    
    public void setFzrq(Date fzrq) {
        this.fzrq = fzrq;
    }
    public String getZslx() {
        return this.zslx;
    }
    
    public void setZslx(String zslx) {
        this.zslx = zslx;
    }
    public String getZsxlh() {
        return this.zsxlh;
    }
    
    public void setZsxlh(String zsxlh) {
        this.zsxlh = zsxlh;
    }
    public BigDecimal getDycs() {
        return this.dycs;
    }
    
    public void setDycs(BigDecimal dycs) {
        this.dycs = dycs;
    }
    public String getGdh() {
        return this.gdh;
    }
    
    public void setGdh(String gdh) {
        this.gdh = gdh;
    }
    public String getDamj() {
        return this.damj;
    }
    
    public void setDamj(String damj) {
        this.damj = damj;
    }
    public String getQt() {
        return this.qt;
    }
    
    public void setQt(String qt) {
        this.qt = qt;
    }
    public String getFj() {
        return this.fj;
    }
    
    public void setFj(String fj) {
        this.fj = fj;
    }
    public String getXgzh() {
        return this.xgzh;
    }
    
    public void setXgzh(String xgzh) {
        this.xgzh = xgzh;
    }
    public String getGlzh() {
        return this.glzh;
    }
    
    public void setGlzh(String glzh) {
        this.glzh = glzh;
    }
    public String getBdcdyh() {
        return this.bdcdyh;
    }
    
    public void setBdcdyh(String bdcdyh) {
        this.bdcdyh = bdcdyh;
    }
    public String getHdpch() {
        return this.hdpch;
    }
    
    public void setHdpch(String hdpch) {
        this.hdpch = hdpch;
    }
    public String getSzpch() {
        return this.szpch;
    }
    
    public void setSzpch(String szpch) {
        this.szpch = szpch;
    }
    public String getZxdjdybh() {
        return this.zxdjdybh;
    }
    
    public void setZxdjdybh(String zxdjdybh) {
        this.zxdjdybh = zxdjdybh;
    }
    public BigDecimal getLifecycle() {
        return this.lifecycle;
    }
    
    public void setLifecycle(BigDecimal lifecycle) {
        this.lifecycle = lifecycle;
    }
    public String getAppid() {
        return this.appid;
    }
    
    public void setAppid(String appid) {
        this.appid = appid;
    }
    public String getYslbh() {
        return this.yslbh;
    }
    
    public void setYslbh(String yslbh) {
        this.yslbh = yslbh;
    }
    public BigDecimal getLifecycle1() {
        return this.lifecycle1;
    }
    
    public void setLifecycle1(BigDecimal lifecycle1) {
        this.lifecycle1 = lifecycle1;
    }
    public String getZl() {
        return this.zl;
    }
    
    public void setZl(String zl) {
        this.zl = zl;
    }
    public String getDjyy1() {
        return this.djyy1;
    }
    
    public void setDjyy1(String djyy1) {
        this.djyy1 = djyy1;
    }
    public String getBdczhtemp() {
        return this.bdczhtemp;
    }
    
    public void setBdczhtemp(String bdczhtemp) {
        this.bdczhtemp = bdczhtemp;
    }
    public String getBdczh1() {
        return this.bdczh1;
    }
    
    public void setBdczh1(String bdczh1) {
        this.bdczh1 = bdczh1;
    }
    public BigDecimal getSfcz() {
        return this.sfcz;
    }
    
    public void setSfcz(BigDecimal sfcz) {
        this.sfcz = sfcz;
    }
    public BigDecimal getFccz() {
        return this.fccz;
    }
    
    public void setFccz(BigDecimal fccz) {
        this.fccz = fccz;
    }
    public BigDecimal getSfcf() {
        return this.sfcf;
    }
    
    public void setSfcf(BigDecimal sfcf) {
        this.sfcf = sfcf;
    }
    public String getYfj() {
        return this.yfj;
    }
    
    public void setYfj(String yfj) {
        this.yfj = yfj;
    }
    public BigDecimal getLifecycle2() {
        return this.lifecycle2;
    }
    
    public void setLifecycle2(BigDecimal lifecycle2) {
        this.lifecycle2 = lifecycle2;
    }
    public String getWz() {
        return this.wz;
    }
    
    public void setWz(String wz) {
        this.wz = wz;
    }
    public String getDzzsxlh() {
        return this.dzzsxlh;
    }
    
    public void setDzzsxlh(String dzzsxlh) {
        this.dzzsxlh = dzzsxlh;
    }
    public String getBdczh2() {
        return this.bdczh2;
    }
    
    public void setBdczh2(String bdczh2) {
        this.bdczh2 = bdczh2;
    }
    public String getRegid() {
        return this.regid;
    }
    
    public void setRegid(String regid) {
        this.regid = regid;
    }
    public BigDecimal getSnum() {
        return this.snum;
    }
    
    public void setSnum(BigDecimal snum) {
        this.snum = snum;
    }
    public String getQtfj() {
        return this.qtfj;
    }
    
    public void setQtfj(String qtfj) {
        this.qtfj = qtfj;
    }
    public String getZjsm() {
        return this.zjsm;
    }
    
    public void setZjsm(String zjsm) {
        this.zjsm = zjsm;
    }


	@Override
	public String getIdName() {
		// TODO Auto-generated method stub
		return "slbh";
	}


	@Override
	public String getDataVersionName() {
		// TODO Auto-generated method stub
		return null;
	}




}


