package com.iawtr.database.dto;
// Generated 2019-1-7 14:12:28 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * DjDy generated by hbm2java
 */
public class DjDy  implements java.io.Serializable ,DtoInterface {
	private static final long serialVersionUID = 1L;

     private String slbh;
     private String djlx;
     private String djyy;
     private String xgzh;
     private Date sqrq;
     private String sqdjyj;
     private String sqdjnr;
     private String dljgmc;
     private String dlrxm;
     private String dlrzjlx;
     private String dlrzjh;
     private String dlrzgzh;
     private String dlrdh;
     private String dljgmc2;
     private String dlrxm2;
     private String dlrzjlx2;
     private String dlrzjh2;
     private String dlrzgzh2;
     private String dlrdh2;
     private String dylx;
     private BigDecimal dysw;
     private String zwr;
     private String zwrzjlx;
     private String zwrzjh;
     private String dyfs;
     private BigDecimal dymj;
     private BigDecimal dymj2;
     private String zjjzwzl;
     private String zjjzwdyfw;
     private BigDecimal bdbzzqse;
     private BigDecimal pgje;
     private String dbfw;
     private String zgzqqdss;
     private BigDecimal zgzqse;
     private String dyqx;
     private Date qlqssj;
     private Date qljssj;
     private String spdw;
     private String spbz;
     private String bdczmh;
     private String ssjc;
     private String jgjc;
     private String fznd;
     private String zsh;
     private String szr;
     private Date djrq;
     private String dbr;
     private String zsr;
     private String fzjg;
     private Date fzrq;
     private String zsxlh;
     private BigDecimal dycs;
     private String gdh;
     private String damj;
     private String qt;
     private String fj;
     private String bdcdyh;
     private String hdpch;
     private String szpch;
     private BigDecimal dybdcdy;
     private BigDecimal lifecycle;
     private String appid;
     private BigDecimal mortgagestatus;
     private String zl;
     private String wz;
     private String ygdjzl;
     private String dzzsxlh;
     private String jebz;

    public DjDy() {
    }

	
    public DjDy(String slbh) {
        this.slbh = slbh;
    }
    public DjDy(String slbh, String djlx, String djyy, String xgzh, Date sqrq, String sqdjyj, String sqdjnr, String dljgmc, String dlrxm, String dlrzjlx, String dlrzjh, String dlrzgzh, String dlrdh, String dljgmc2, String dlrxm2, String dlrzjlx2, String dlrzjh2, String dlrzgzh2, String dlrdh2, String dylx, BigDecimal dysw, String zwr, String zwrzjlx, String zwrzjh, String dyfs, BigDecimal dymj, BigDecimal dymj2, String zjjzwzl, String zjjzwdyfw, BigDecimal bdbzzqse, BigDecimal pgje, String dbfw, String zgzqqdss, BigDecimal zgzqse, String dyqx, Date qlqssj, Date qljssj, String spdw, String spbz, String bdczmh, String ssjc, String jgjc, String fznd, String zsh, String szr, Date djrq, String dbr, String zsr, String fzjg, Date fzrq, String zsxlh, BigDecimal dycs, String gdh, String damj, String qt, String fj, String bdcdyh, String hdpch, String szpch, BigDecimal dybdcdy, BigDecimal lifecycle, String appid, BigDecimal mortgagestatus, String zl, String wz, String ygdjzl, String dzzsxlh, String jebz) {
       this.slbh = slbh;
       this.djlx = djlx;
       this.djyy = djyy;
       this.xgzh = xgzh;
       this.sqrq = sqrq;
       this.sqdjyj = sqdjyj;
       this.sqdjnr = sqdjnr;
       this.dljgmc = dljgmc;
       this.dlrxm = dlrxm;
       this.dlrzjlx = dlrzjlx;
       this.dlrzjh = dlrzjh;
       this.dlrzgzh = dlrzgzh;
       this.dlrdh = dlrdh;
       this.dljgmc2 = dljgmc2;
       this.dlrxm2 = dlrxm2;
       this.dlrzjlx2 = dlrzjlx2;
       this.dlrzjh2 = dlrzjh2;
       this.dlrzgzh2 = dlrzgzh2;
       this.dlrdh2 = dlrdh2;
       this.dylx = dylx;
       this.dysw = dysw;
       this.zwr = zwr;
       this.zwrzjlx = zwrzjlx;
       this.zwrzjh = zwrzjh;
       this.dyfs = dyfs;
       this.dymj = dymj;
       this.dymj2 = dymj2;
       this.zjjzwzl = zjjzwzl;
       this.zjjzwdyfw = zjjzwdyfw;
       this.bdbzzqse = bdbzzqse;
       this.pgje = pgje;
       this.dbfw = dbfw;
       this.zgzqqdss = zgzqqdss;
       this.zgzqse = zgzqse;
       this.dyqx = dyqx;
       this.qlqssj = qlqssj;
       this.qljssj = qljssj;
       this.spdw = spdw;
       this.spbz = spbz;
       this.bdczmh = bdczmh;
       this.ssjc = ssjc;
       this.jgjc = jgjc;
       this.fznd = fznd;
       this.zsh = zsh;
       this.szr = szr;
       this.djrq = djrq;
       this.dbr = dbr;
       this.zsr = zsr;
       this.fzjg = fzjg;
       this.fzrq = fzrq;
       this.zsxlh = zsxlh;
       this.dycs = dycs;
       this.gdh = gdh;
       this.damj = damj;
       this.qt = qt;
       this.fj = fj;
       this.bdcdyh = bdcdyh;
       this.hdpch = hdpch;
       this.szpch = szpch;
       this.dybdcdy = dybdcdy;
       this.lifecycle = lifecycle;
       this.appid = appid;
       this.mortgagestatus = mortgagestatus;
       this.zl = zl;
       this.wz = wz;
       this.ygdjzl = ygdjzl;
       this.dzzsxlh = dzzsxlh;
       this.jebz = jebz;
    }
   
    public String getSlbh() {
        return this.slbh;
    }
    
    public void setSlbh(String slbh) {
        this.slbh = slbh;
    }
    public String getDjlx() {
        return this.djlx;
    }
    
    public void setDjlx(String djlx) {
        this.djlx = djlx;
    }
    public String getDjyy() {
        return this.djyy;
    }
    
    public void setDjyy(String djyy) {
        this.djyy = djyy;
    }
    public String getXgzh() {
        return this.xgzh;
    }
    
    public void setXgzh(String xgzh) {
        this.xgzh = xgzh;
    }
    public Date getSqrq() {
        return this.sqrq;
    }
    
    public void setSqrq(Date sqrq) {
        this.sqrq = sqrq;
    }
    public String getSqdjyj() {
        return this.sqdjyj;
    }
    
    public void setSqdjyj(String sqdjyj) {
        this.sqdjyj = sqdjyj;
    }
    public String getSqdjnr() {
        return this.sqdjnr;
    }
    
    public void setSqdjnr(String sqdjnr) {
        this.sqdjnr = sqdjnr;
    }
    public String getDljgmc() {
        return this.dljgmc;
    }
    
    public void setDljgmc(String dljgmc) {
        this.dljgmc = dljgmc;
    }
    public String getDlrxm() {
        return this.dlrxm;
    }
    
    public void setDlrxm(String dlrxm) {
        this.dlrxm = dlrxm;
    }
    public String getDlrzjlx() {
        return this.dlrzjlx;
    }
    
    public void setDlrzjlx(String dlrzjlx) {
        this.dlrzjlx = dlrzjlx;
    }
    public String getDlrzjh() {
        return this.dlrzjh;
    }
    
    public void setDlrzjh(String dlrzjh) {
        this.dlrzjh = dlrzjh;
    }
    public String getDlrzgzh() {
        return this.dlrzgzh;
    }
    
    public void setDlrzgzh(String dlrzgzh) {
        this.dlrzgzh = dlrzgzh;
    }
    public String getDlrdh() {
        return this.dlrdh;
    }
    
    public void setDlrdh(String dlrdh) {
        this.dlrdh = dlrdh;
    }
    public String getDljgmc2() {
        return this.dljgmc2;
    }
    
    public void setDljgmc2(String dljgmc2) {
        this.dljgmc2 = dljgmc2;
    }
    public String getDlrxm2() {
        return this.dlrxm2;
    }
    
    public void setDlrxm2(String dlrxm2) {
        this.dlrxm2 = dlrxm2;
    }
    public String getDlrzjlx2() {
        return this.dlrzjlx2;
    }
    
    public void setDlrzjlx2(String dlrzjlx2) {
        this.dlrzjlx2 = dlrzjlx2;
    }
    public String getDlrzjh2() {
        return this.dlrzjh2;
    }
    
    public void setDlrzjh2(String dlrzjh2) {
        this.dlrzjh2 = dlrzjh2;
    }
    public String getDlrzgzh2() {
        return this.dlrzgzh2;
    }
    
    public void setDlrzgzh2(String dlrzgzh2) {
        this.dlrzgzh2 = dlrzgzh2;
    }
    public String getDlrdh2() {
        return this.dlrdh2;
    }
    
    public void setDlrdh2(String dlrdh2) {
        this.dlrdh2 = dlrdh2;
    }
    public String getDylx() {
        return this.dylx;
    }
    
    public void setDylx(String dylx) {
        this.dylx = dylx;
    }
    public BigDecimal getDysw() {
        return this.dysw;
    }
    
    public void setDysw(BigDecimal dysw) {
        this.dysw = dysw;
    }
    public String getZwr() {
        return this.zwr;
    }
    
    public void setZwr(String zwr) {
        this.zwr = zwr;
    }
    public String getZwrzjlx() {
        return this.zwrzjlx;
    }
    
    public void setZwrzjlx(String zwrzjlx) {
        this.zwrzjlx = zwrzjlx;
    }
    public String getZwrzjh() {
        return this.zwrzjh;
    }
    
    public void setZwrzjh(String zwrzjh) {
        this.zwrzjh = zwrzjh;
    }
    public String getDyfs() {
        return this.dyfs;
    }
    
    public void setDyfs(String dyfs) {
        this.dyfs = dyfs;
    }
    public BigDecimal getDymj() {
        return this.dymj;
    }
    
    public void setDymj(BigDecimal dymj) {
        this.dymj = dymj;
    }
    public BigDecimal getDymj2() {
        return this.dymj2;
    }
    
    public void setDymj2(BigDecimal dymj2) {
        this.dymj2 = dymj2;
    }
    public String getZjjzwzl() {
        return this.zjjzwzl;
    }
    
    public void setZjjzwzl(String zjjzwzl) {
        this.zjjzwzl = zjjzwzl;
    }
    public String getZjjzwdyfw() {
        return this.zjjzwdyfw;
    }
    
    public void setZjjzwdyfw(String zjjzwdyfw) {
        this.zjjzwdyfw = zjjzwdyfw;
    }
    public BigDecimal getBdbzzqse() {
        return this.bdbzzqse;
    }
    
    public void setBdbzzqse(BigDecimal bdbzzqse) {
        this.bdbzzqse = bdbzzqse;
    }
    public BigDecimal getPgje() {
        return this.pgje;
    }
    
    public void setPgje(BigDecimal pgje) {
        this.pgje = pgje;
    }
    public String getDbfw() {
        return this.dbfw;
    }
    
    public void setDbfw(String dbfw) {
        this.dbfw = dbfw;
    }
    public String getZgzqqdss() {
        return this.zgzqqdss;
    }
    
    public void setZgzqqdss(String zgzqqdss) {
        this.zgzqqdss = zgzqqdss;
    }
    public BigDecimal getZgzqse() {
        return this.zgzqse;
    }
    
    public void setZgzqse(BigDecimal zgzqse) {
        this.zgzqse = zgzqse;
    }
    public String getDyqx() {
        return this.dyqx;
    }
    
    public void setDyqx(String dyqx) {
        this.dyqx = dyqx;
    }
    public Date getQlqssj() {
        return this.qlqssj;
    }
    
    public void setQlqssj(Date qlqssj) {
        this.qlqssj = qlqssj;
    }
    public Date getQljssj() {
        return this.qljssj;
    }
    
    public void setQljssj(Date qljssj) {
        this.qljssj = qljssj;
    }
    public String getSpdw() {
        return this.spdw;
    }
    
    public void setSpdw(String spdw) {
        this.spdw = spdw;
    }
    public String getSpbz() {
        return this.spbz;
    }
    
    public void setSpbz(String spbz) {
        this.spbz = spbz;
    }
    public String getBdczmh() {
        return this.bdczmh;
    }
    
    public void setBdczmh(String bdczmh) {
        this.bdczmh = bdczmh;
    }
    public String getSsjc() {
        return this.ssjc;
    }
    
    public void setSsjc(String ssjc) {
        this.ssjc = ssjc;
    }
    public String getJgjc() {
        return this.jgjc;
    }
    
    public void setJgjc(String jgjc) {
        this.jgjc = jgjc;
    }
    public String getFznd() {
        return this.fznd;
    }
    
    public void setFznd(String fznd) {
        this.fznd = fznd;
    }
    public String getZsh() {
        return this.zsh;
    }
    
    public void setZsh(String zsh) {
        this.zsh = zsh;
    }
    public String getSzr() {
        return this.szr;
    }
    
    public void setSzr(String szr) {
        this.szr = szr;
    }
    public Date getDjrq() {
        return this.djrq;
    }
    
    public void setDjrq(Date djrq) {
        this.djrq = djrq;
    }
    public String getDbr() {
        return this.dbr;
    }
    
    public void setDbr(String dbr) {
        this.dbr = dbr;
    }
    public String getZsr() {
        return this.zsr;
    }
    
    public void setZsr(String zsr) {
        this.zsr = zsr;
    }
    public String getFzjg() {
        return this.fzjg;
    }
    
    public void setFzjg(String fzjg) {
        this.fzjg = fzjg;
    }
    public Date getFzrq() {
        return this.fzrq;
    }
    
    public void setFzrq(Date fzrq) {
        this.fzrq = fzrq;
    }
    public String getZsxlh() {
        return this.zsxlh;
    }
    
    public void setZsxlh(String zsxlh) {
        this.zsxlh = zsxlh;
    }
    public BigDecimal getDycs() {
        return this.dycs;
    }
    
    public void setDycs(BigDecimal dycs) {
        this.dycs = dycs;
    }
    public String getGdh() {
        return this.gdh;
    }
    
    public void setGdh(String gdh) {
        this.gdh = gdh;
    }
    public String getDamj() {
        return this.damj;
    }
    
    public void setDamj(String damj) {
        this.damj = damj;
    }
    public String getQt() {
        return this.qt;
    }
    
    public void setQt(String qt) {
        this.qt = qt;
    }
    public String getFj() {
        return this.fj;
    }
    
    public void setFj(String fj) {
        this.fj = fj;
    }
    public String getBdcdyh() {
        return this.bdcdyh;
    }
    
    public void setBdcdyh(String bdcdyh) {
        this.bdcdyh = bdcdyh;
    }
    public String getHdpch() {
        return this.hdpch;
    }
    
    public void setHdpch(String hdpch) {
        this.hdpch = hdpch;
    }
    public String getSzpch() {
        return this.szpch;
    }
    
    public void setSzpch(String szpch) {
        this.szpch = szpch;
    }
    public BigDecimal getDybdcdy() {
        return this.dybdcdy;
    }
    
    public void setDybdcdy(BigDecimal dybdcdy) {
        this.dybdcdy = dybdcdy;
    }
    public BigDecimal getLifecycle() {
        return this.lifecycle;
    }
    
    public void setLifecycle(BigDecimal lifecycle) {
        this.lifecycle = lifecycle;
    }
    public String getAppid() {
        return this.appid;
    }
    
    public void setAppid(String appid) {
        this.appid = appid;
    }
    public BigDecimal getMortgagestatus() {
        return this.mortgagestatus;
    }
    
    public void setMortgagestatus(BigDecimal mortgagestatus) {
        this.mortgagestatus = mortgagestatus;
    }
    public String getZl() {
        return this.zl;
    }
    
    public void setZl(String zl) {
        this.zl = zl;
    }
    public String getWz() {
        return this.wz;
    }
    
    public void setWz(String wz) {
        this.wz = wz;
    }
    public String getYgdjzl() {
        return this.ygdjzl;
    }
    
    public void setYgdjzl(String ygdjzl) {
        this.ygdjzl = ygdjzl;
    }
    public String getDzzsxlh() {
        return this.dzzsxlh;
    }
    
    public void setDzzsxlh(String dzzsxlh) {
        this.dzzsxlh = dzzsxlh;
    }
    public String getJebz() {
        return this.jebz;
    }
    
    public void setJebz(String jebz) {
        this.jebz = jebz;
    }


	@Override
	public String getIdName() {
		// TODO Auto-generated method stub
		return "slbh";
	}


	@Override
	public String getDataVersionName() {
		// TODO Auto-generated method stub
		return null;
	}




}


