package com.iawtr.database.dto;
// Generated 2019-1-7 14:12:28 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;

/**
 * DjQlr generated by hbm2java
 */
public class DjQlr  implements java.io.Serializable ,DtoInterface {
	private static final long serialVersionUID = 1L;

     private String qlrid;
     private String qlrmc;
     private BigDecimal sxh;
     private String zjlb;
     private String zjhm;
     private String fzjg;
     private String sshy;
     private String gj;
     private String hjszss;
     private String xb;
     private Blob zp;
     private String dh;
     private String dz;
     private String yb;
     private String gzdw;
     private String dzyj;
     private String qlrxz;
     private String qlrzt;
     private String xyzt;
     private String fqlr;
     private String gx;
     private String jtrk;
     private String nsrsbh;
     private String frdbxm;
     private String frdbzjlx;
     private String frdbzjh;
     private String frdbdhhm;
     private String sjzgbm;
     private String txdz;
     private Blob zw1;
     private Blob zwtzm1;
     private Blob zw2;
     private Blob zwtzm2;
     private Blob zw3;
     private Blob zwtzm3;
     private BigDecimal xydj;
     private Date yxqsrq;
     private Date yxzzrq;

    public DjQlr() {
    }

	
    public DjQlr(String qlrid) {
        this.qlrid = qlrid;
    }
    public DjQlr(String qlrid, String qlrmc, BigDecimal sxh, String zjlb, String zjhm, String fzjg, String sshy, String gj, String hjszss, String xb, Blob zp, String dh, String dz, String yb, String gzdw, String dzyj, String qlrxz, String qlrzt, String xyzt, String fqlr, String gx, String jtrk, String nsrsbh, String frdbxm, String frdbzjlx, String frdbzjh, String frdbdhhm, String sjzgbm, String txdz, Blob zw1, Blob zwtzm1, Blob zw2, Blob zwtzm2, Blob zw3, Blob zwtzm3, BigDecimal xydj, Date yxqsrq, Date yxzzrq) {
       this.qlrid = qlrid;
       this.qlrmc = qlrmc;
       this.sxh = sxh;
       this.zjlb = zjlb;
       this.zjhm = zjhm;
       this.fzjg = fzjg;
       this.sshy = sshy;
       this.gj = gj;
       this.hjszss = hjszss;
       this.xb = xb;
       this.zp = zp;
       this.dh = dh;
       this.dz = dz;
       this.yb = yb;
       this.gzdw = gzdw;
       this.dzyj = dzyj;
       this.qlrxz = qlrxz;
       this.qlrzt = qlrzt;
       this.xyzt = xyzt;
       this.fqlr = fqlr;
       this.gx = gx;
       this.jtrk = jtrk;
       this.nsrsbh = nsrsbh;
       this.frdbxm = frdbxm;
       this.frdbzjlx = frdbzjlx;
       this.frdbzjh = frdbzjh;
       this.frdbdhhm = frdbdhhm;
       this.sjzgbm = sjzgbm;
       this.txdz = txdz;
       this.zw1 = zw1;
       this.zwtzm1 = zwtzm1;
       this.zw2 = zw2;
       this.zwtzm2 = zwtzm2;
       this.zw3 = zw3;
       this.zwtzm3 = zwtzm3;
       this.xydj = xydj;
       this.yxqsrq = yxqsrq;
       this.yxzzrq = yxzzrq;
    }
   
    public String getQlrid() {
        return this.qlrid;
    }
    
    public void setQlrid(String qlrid) {
        this.qlrid = qlrid;
    }
    public String getQlrmc() {
        return this.qlrmc;
    }
    
    public void setQlrmc(String qlrmc) {
        this.qlrmc = qlrmc;
    }
    public BigDecimal getSxh() {
        return this.sxh;
    }
    
    public void setSxh(BigDecimal sxh) {
        this.sxh = sxh;
    }
    public String getZjlb() {
        return this.zjlb;
    }
    
    public void setZjlb(String zjlb) {
        this.zjlb = zjlb;
    }
    public String getZjhm() {
        return this.zjhm;
    }
    
    public void setZjhm(String zjhm) {
        this.zjhm = zjhm;
    }
    public String getFzjg() {
        return this.fzjg;
    }
    
    public void setFzjg(String fzjg) {
        this.fzjg = fzjg;
    }
    public String getSshy() {
        return this.sshy;
    }
    
    public void setSshy(String sshy) {
        this.sshy = sshy;
    }
    public String getGj() {
        return this.gj;
    }
    
    public void setGj(String gj) {
        this.gj = gj;
    }
    public String getHjszss() {
        return this.hjszss;
    }
    
    public void setHjszss(String hjszss) {
        this.hjszss = hjszss;
    }
    public String getXb() {
        return this.xb;
    }
    
    public void setXb(String xb) {
        this.xb = xb;
    }
    public Blob getZp() {
        return this.zp;
    }
    
    public void setZp(Blob zp) {
        this.zp = zp;
    }
    public String getDh() {
        return this.dh;
    }
    
    public void setDh(String dh) {
        this.dh = dh;
    }
    public String getDz() {
        return this.dz;
    }
    
    public void setDz(String dz) {
        this.dz = dz;
    }
    public String getYb() {
        return this.yb;
    }
    
    public void setYb(String yb) {
        this.yb = yb;
    }
    public String getGzdw() {
        return this.gzdw;
    }
    
    public void setGzdw(String gzdw) {
        this.gzdw = gzdw;
    }
    public String getDzyj() {
        return this.dzyj;
    }
    
    public void setDzyj(String dzyj) {
        this.dzyj = dzyj;
    }
    public String getQlrxz() {
        return this.qlrxz;
    }
    
    public void setQlrxz(String qlrxz) {
        this.qlrxz = qlrxz;
    }
    public String getQlrzt() {
        return this.qlrzt;
    }
    
    public void setQlrzt(String qlrzt) {
        this.qlrzt = qlrzt;
    }
    public String getXyzt() {
        return this.xyzt;
    }
    
    public void setXyzt(String xyzt) {
        this.xyzt = xyzt;
    }
    public String getFqlr() {
        return this.fqlr;
    }
    
    public void setFqlr(String fqlr) {
        this.fqlr = fqlr;
    }
    public String getGx() {
        return this.gx;
    }
    
    public void setGx(String gx) {
        this.gx = gx;
    }
    public String getJtrk() {
        return this.jtrk;
    }
    
    public void setJtrk(String jtrk) {
        this.jtrk = jtrk;
    }
    public String getNsrsbh() {
        return this.nsrsbh;
    }
    
    public void setNsrsbh(String nsrsbh) {
        this.nsrsbh = nsrsbh;
    }
    public String getFrdbxm() {
        return this.frdbxm;
    }
    
    public void setFrdbxm(String frdbxm) {
        this.frdbxm = frdbxm;
    }
    public String getFrdbzjlx() {
        return this.frdbzjlx;
    }
    
    public void setFrdbzjlx(String frdbzjlx) {
        this.frdbzjlx = frdbzjlx;
    }
    public String getFrdbzjh() {
        return this.frdbzjh;
    }
    
    public void setFrdbzjh(String frdbzjh) {
        this.frdbzjh = frdbzjh;
    }
    public String getFrdbdhhm() {
        return this.frdbdhhm;
    }
    
    public void setFrdbdhhm(String frdbdhhm) {
        this.frdbdhhm = frdbdhhm;
    }
    public String getSjzgbm() {
        return this.sjzgbm;
    }
    
    public void setSjzgbm(String sjzgbm) {
        this.sjzgbm = sjzgbm;
    }
    public String getTxdz() {
        return this.txdz;
    }
    
    public void setTxdz(String txdz) {
        this.txdz = txdz;
    }
    public Blob getZw1() {
        return this.zw1;
    }
    
    public void setZw1(Blob zw1) {
        this.zw1 = zw1;
    }
    public Blob getZwtzm1() {
        return this.zwtzm1;
    }
    
    public void setZwtzm1(Blob zwtzm1) {
        this.zwtzm1 = zwtzm1;
    }
    public Blob getZw2() {
        return this.zw2;
    }
    
    public void setZw2(Blob zw2) {
        this.zw2 = zw2;
    }
    public Blob getZwtzm2() {
        return this.zwtzm2;
    }
    
    public void setZwtzm2(Blob zwtzm2) {
        this.zwtzm2 = zwtzm2;
    }
    public Blob getZw3() {
        return this.zw3;
    }
    
    public void setZw3(Blob zw3) {
        this.zw3 = zw3;
    }
    public Blob getZwtzm3() {
        return this.zwtzm3;
    }
    
    public void setZwtzm3(Blob zwtzm3) {
        this.zwtzm3 = zwtzm3;
    }
    public BigDecimal getXydj() {
        return this.xydj;
    }
    
    public void setXydj(BigDecimal xydj) {
        this.xydj = xydj;
    }
    public Date getYxqsrq() {
        return this.yxqsrq;
    }
    
    public void setYxqsrq(Date yxqsrq) {
        this.yxqsrq = yxqsrq;
    }
    public Date getYxzzrq() {
        return this.yxzzrq;
    }
    
    public void setYxzzrq(Date yxzzrq) {
        this.yxzzrq = yxzzrq;
    }


	@Override
	public String getIdName() {
		// TODO Auto-generated method stub
		return "qlrid";
	}


	@Override
	public String getDataVersionName() {
		// TODO Auto-generated method stub
		return null;
	}




}


