package com.iawtr.database.dto;
// Generated 2019-1-7 14:12:28 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * DjQlrgl generated by hbm2java
 */
public class DjQlrgl  implements java.io.Serializable ,DtoInterface {
	private static final long serialVersionUID = 1L;

     private String glbm;
     private String slbh;
     private String ywbm;
     private String qlrid;
     private String gyfs;
     private String gyfe;
     private String czfs;
     private String czbh;
     private String zsxlh;
     private BigDecimal sxh;
     private String qlrlx;
     private BigDecimal lifecycle;
     private String qlrmc;
     private String gx;
     private String appid;
     private String oldbz;
     private String bdczh;
     private BigDecimal sfcf;
     private String zjhm;
     private String zjlb;
     private String dzzsxlh;
     private String dh;

    public DjQlrgl() {
    }

	
    public DjQlrgl(String glbm, String qlrid) {
        this.glbm = glbm;
        this.qlrid = qlrid;
    }
    public DjQlrgl(String glbm, String slbh, String ywbm, String qlrid, String gyfs, String gyfe, String czfs, String czbh, String zsxlh, BigDecimal sxh, String qlrlx, BigDecimal lifecycle, String qlrmc, String gx, String appid, String oldbz, String bdczh, BigDecimal sfcf, String zjhm, String zjlb, String dzzsxlh, String dh) {
       this.glbm = glbm;
       this.slbh = slbh;
       this.ywbm = ywbm;
       this.qlrid = qlrid;
       this.gyfs = gyfs;
       this.gyfe = gyfe;
       this.czfs = czfs;
       this.czbh = czbh;
       this.zsxlh = zsxlh;
       this.sxh = sxh;
       this.qlrlx = qlrlx;
       this.lifecycle = lifecycle;
       this.qlrmc = qlrmc;
       this.gx = gx;
       this.appid = appid;
       this.oldbz = oldbz;
       this.bdczh = bdczh;
       this.sfcf = sfcf;
       this.zjhm = zjhm;
       this.zjlb = zjlb;
       this.dzzsxlh = dzzsxlh;
       this.dh = dh;
    }
   
    public String getGlbm() {
        return this.glbm;
    }
    
    public void setGlbm(String glbm) {
        this.glbm = glbm;
    }
    public String getSlbh() {
        return this.slbh;
    }
    
    public void setSlbh(String slbh) {
        this.slbh = slbh;
    }
    public String getYwbm() {
        return this.ywbm;
    }
    
    public void setYwbm(String ywbm) {
        this.ywbm = ywbm;
    }
    public String getQlrid() {
        return this.qlrid;
    }
    
    public void setQlrid(String qlrid) {
        this.qlrid = qlrid;
    }
    public String getGyfs() {
        return this.gyfs;
    }
    
    public void setGyfs(String gyfs) {
        this.gyfs = gyfs;
    }
    public String getGyfe() {
        return this.gyfe;
    }
    
    public void setGyfe(String gyfe) {
        this.gyfe = gyfe;
    }
    public String getCzfs() {
        return this.czfs;
    }
    
    public void setCzfs(String czfs) {
        this.czfs = czfs;
    }
    public String getCzbh() {
        return this.czbh;
    }
    
    public void setCzbh(String czbh) {
        this.czbh = czbh;
    }
    public String getZsxlh() {
        return this.zsxlh;
    }
    
    public void setZsxlh(String zsxlh) {
        this.zsxlh = zsxlh;
    }
    public BigDecimal getSxh() {
        return this.sxh;
    }
    
    public void setSxh(BigDecimal sxh) {
        this.sxh = sxh;
    }
    public String getQlrlx() {
        return this.qlrlx;
    }
    
    public void setQlrlx(String qlrlx) {
        this.qlrlx = qlrlx;
    }
    public BigDecimal getLifecycle() {
        return this.lifecycle;
    }
    
    public void setLifecycle(BigDecimal lifecycle) {
        this.lifecycle = lifecycle;
    }
    public String getQlrmc() {
        return this.qlrmc;
    }
    
    public void setQlrmc(String qlrmc) {
        this.qlrmc = qlrmc;
    }
    public String getGx() {
        return this.gx;
    }
    
    public void setGx(String gx) {
        this.gx = gx;
    }
    public String getAppid() {
        return this.appid;
    }
    
    public void setAppid(String appid) {
        this.appid = appid;
    }
    public String getOldbz() {
        return this.oldbz;
    }
    
    public void setOldbz(String oldbz) {
        this.oldbz = oldbz;
    }
    public String getBdczh() {
        return this.bdczh;
    }
    
    public void setBdczh(String bdczh) {
        this.bdczh = bdczh;
    }
    public BigDecimal getSfcf() {
        return this.sfcf;
    }
    
    public void setSfcf(BigDecimal sfcf) {
        this.sfcf = sfcf;
    }
    public String getZjhm() {
        return this.zjhm;
    }
    
    public void setZjhm(String zjhm) {
        this.zjhm = zjhm;
    }
    public String getZjlb() {
        return this.zjlb;
    }
    
    public void setZjlb(String zjlb) {
        this.zjlb = zjlb;
    }
    public String getDzzsxlh() {
        return this.dzzsxlh;
    }
    
    public void setDzzsxlh(String dzzsxlh) {
        this.dzzsxlh = dzzsxlh;
    }
    public String getDh() {
        return this.dh;
    }
    
    public void setDh(String dh) {
        this.dh = dh;
    }


	@Override
	public String getIdName() {
		// TODO Auto-generated method stub
		return "glbm";
	}


	@Override
	public String getDataVersionName() {
		// TODO Auto-generated method stub
		return null;
	}




}


