package com.iawtr.database.dto;
// Generated 2019-1-7 14:12:28 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;

/**
 * DjSjd generated by hbm2java
 */
public class DjSjd  implements java.io.Serializable ,DtoInterface {
	private static final long serialVersionUID = 1L;

     private String slbh;
     private String djdl;
     private String djxl;
     private String lclx;
     private String lcbm;
     private String lcmc;
     private String zl;
     private String sjr;
     private Date sjsj;
     private Date cnsj;
     private String qxdm;
     private String tzrxm;
     private String tzfs;
     private String tzrdh;
     private String tzryddh;
     private String tzrdzyj;
     private String tzrtxdz;
     private String cxmm;
     private String sjmc;
     private String sjlx;
     private BigDecimal sjsl;
     private BigDecimal ys;
     private String sfsybz;
     private String sfewsj;
     private String sfbcsj;
     private String zrks;
     private String zrr;
     private String yxj;
     private String sjbz;
     private String bcsm;
     private String fcslh;
     private String fcdjlx;
     private String fchid;
     private String bizmsgid;
     private String jrywbm;
     private BigDecimal sbzt;
     private BigDecimal sbxzcs;
     private String certinum;
     private BigDecimal sbstzt;
     private String htbh;
     private String pch;
     private String jybh;
     private String ajzt;
     private Blob xczp;
     private String prjid;
     private String lzqk;
     private String tdzh;
     private String certiinfo;
     private BigDecimal jhzt;
     private BigDecimal sfcf;
     private String dlrxm;
     private String dlrzjhm;
     private String sharekey;
     private Date sharetime;
     private String sharestate;
     private String qxkz;
     private String cgzt;
     private String wwsqbh;
     private String wwyybh;
     private String qyxs;
     private BigDecimal zkbs;
     private Date sharetimeFc;
     private String sharestateFc;
     private String ggXmbh;
     private String sbjg;
     private BigDecimal sbcs;
     private Date sbsj;
     private String sharestateZw;
     private String tszt;

    public DjSjd() {
    }

	
    public DjSjd(String slbh) {
        this.slbh = slbh;
    }
    public DjSjd(String slbh, String djdl, String djxl, String lclx, String lcbm, String lcmc, String zl, String sjr, Date sjsj, Date cnsj, String qxdm, String tzrxm, String tzfs, String tzrdh, String tzryddh, String tzrdzyj, String tzrtxdz, String cxmm, String sjmc, String sjlx, BigDecimal sjsl, BigDecimal ys, String sfsybz, String sfewsj, String sfbcsj, String zrks, String zrr, String yxj, String sjbz, String bcsm, String fcslh, String fcdjlx, String fchid, String bizmsgid, String jrywbm, BigDecimal sbzt, BigDecimal sbxzcs, String certinum, BigDecimal sbstzt, String htbh, String pch, String jybh, String ajzt, Blob xczp, String prjid, String lzqk, String tdzh, String certiinfo, BigDecimal jhzt, BigDecimal sfcf, String dlrxm, String dlrzjhm, String sharekey, Date sharetime, String sharestate, String qxkz, String cgzt, String wwsqbh, String wwyybh, String qyxs, BigDecimal zkbs, Date sharetimeFc, String sharestateFc, String ggXmbh, String sbjg, BigDecimal sbcs, Date sbsj, String sharestateZw, String tszt) {
       this.slbh = slbh;
       this.djdl = djdl;
       this.djxl = djxl;
       this.lclx = lclx;
       this.lcbm = lcbm;
       this.lcmc = lcmc;
       this.zl = zl;
       this.sjr = sjr;
       this.sjsj = sjsj;
       this.cnsj = cnsj;
       this.qxdm = qxdm;
       this.tzrxm = tzrxm;
       this.tzfs = tzfs;
       this.tzrdh = tzrdh;
       this.tzryddh = tzryddh;
       this.tzrdzyj = tzrdzyj;
       this.tzrtxdz = tzrtxdz;
       this.cxmm = cxmm;
       this.sjmc = sjmc;
       this.sjlx = sjlx;
       this.sjsl = sjsl;
       this.ys = ys;
       this.sfsybz = sfsybz;
       this.sfewsj = sfewsj;
       this.sfbcsj = sfbcsj;
       this.zrks = zrks;
       this.zrr = zrr;
       this.yxj = yxj;
       this.sjbz = sjbz;
       this.bcsm = bcsm;
       this.fcslh = fcslh;
       this.fcdjlx = fcdjlx;
       this.fchid = fchid;
       this.bizmsgid = bizmsgid;
       this.jrywbm = jrywbm;
       this.sbzt = sbzt;
       this.sbxzcs = sbxzcs;
       this.certinum = certinum;
       this.sbstzt = sbstzt;
       this.htbh = htbh;
       this.pch = pch;
       this.jybh = jybh;
       this.ajzt = ajzt;
       this.xczp = xczp;
       this.prjid = prjid;
       this.lzqk = lzqk;
       this.tdzh = tdzh;
       this.certiinfo = certiinfo;
       this.jhzt = jhzt;
       this.sfcf = sfcf;
       this.dlrxm = dlrxm;
       this.dlrzjhm = dlrzjhm;
       this.sharekey = sharekey;
       this.sharetime = sharetime;
       this.sharestate = sharestate;
       this.qxkz = qxkz;
       this.cgzt = cgzt;
       this.wwsqbh = wwsqbh;
       this.wwyybh = wwyybh;
       this.qyxs = qyxs;
       this.zkbs = zkbs;
       this.sharetimeFc = sharetimeFc;
       this.sharestateFc = sharestateFc;
       this.ggXmbh = ggXmbh;
       this.sbjg = sbjg;
       this.sbcs = sbcs;
       this.sbsj = sbsj;
       this.sharestateZw = sharestateZw;
       this.tszt = tszt;
    }
   
    public String getSlbh() {
        return this.slbh;
    }
    
    public void setSlbh(String slbh) {
        this.slbh = slbh;
    }
    public String getDjdl() {
        return this.djdl;
    }
    
    public void setDjdl(String djdl) {
        this.djdl = djdl;
    }
    public String getDjxl() {
        return this.djxl;
    }
    
    public void setDjxl(String djxl) {
        this.djxl = djxl;
    }
    public String getLclx() {
        return this.lclx;
    }
    
    public void setLclx(String lclx) {
        this.lclx = lclx;
    }
    public String getLcbm() {
        return this.lcbm;
    }
    
    public void setLcbm(String lcbm) {
        this.lcbm = lcbm;
    }
    public String getLcmc() {
        return this.lcmc;
    }
    
    public void setLcmc(String lcmc) {
        this.lcmc = lcmc;
    }
    public String getZl() {
        return this.zl;
    }
    
    public void setZl(String zl) {
        this.zl = zl;
    }
    public String getSjr() {
        return this.sjr;
    }
    
    public void setSjr(String sjr) {
        this.sjr = sjr;
    }
    public Date getSjsj() {
        return this.sjsj;
    }
    
    public void setSjsj(Date sjsj) {
        this.sjsj = sjsj;
    }
    public Date getCnsj() {
        return this.cnsj;
    }
    
    public void setCnsj(Date cnsj) {
        this.cnsj = cnsj;
    }
    public String getQxdm() {
        return this.qxdm;
    }
    
    public void setQxdm(String qxdm) {
        this.qxdm = qxdm;
    }
    public String getTzrxm() {
        return this.tzrxm;
    }
    
    public void setTzrxm(String tzrxm) {
        this.tzrxm = tzrxm;
    }
    public String getTzfs() {
        return this.tzfs;
    }
    
    public void setTzfs(String tzfs) {
        this.tzfs = tzfs;
    }
    public String getTzrdh() {
        return this.tzrdh;
    }
    
    public void setTzrdh(String tzrdh) {
        this.tzrdh = tzrdh;
    }
    public String getTzryddh() {
        return this.tzryddh;
    }
    
    public void setTzryddh(String tzryddh) {
        this.tzryddh = tzryddh;
    }
    public String getTzrdzyj() {
        return this.tzrdzyj;
    }
    
    public void setTzrdzyj(String tzrdzyj) {
        this.tzrdzyj = tzrdzyj;
    }
    public String getTzrtxdz() {
        return this.tzrtxdz;
    }
    
    public void setTzrtxdz(String tzrtxdz) {
        this.tzrtxdz = tzrtxdz;
    }
    public String getCxmm() {
        return this.cxmm;
    }
    
    public void setCxmm(String cxmm) {
        this.cxmm = cxmm;
    }
    public String getSjmc() {
        return this.sjmc;
    }
    
    public void setSjmc(String sjmc) {
        this.sjmc = sjmc;
    }
    public String getSjlx() {
        return this.sjlx;
    }
    
    public void setSjlx(String sjlx) {
        this.sjlx = sjlx;
    }
    public BigDecimal getSjsl() {
        return this.sjsl;
    }
    
    public void setSjsl(BigDecimal sjsl) {
        this.sjsl = sjsl;
    }
    public BigDecimal getYs() {
        return this.ys;
    }
    
    public void setYs(BigDecimal ys) {
        this.ys = ys;
    }
    public String getSfsybz() {
        return this.sfsybz;
    }
    
    public void setSfsybz(String sfsybz) {
        this.sfsybz = sfsybz;
    }
    public String getSfewsj() {
        return this.sfewsj;
    }
    
    public void setSfewsj(String sfewsj) {
        this.sfewsj = sfewsj;
    }
    public String getSfbcsj() {
        return this.sfbcsj;
    }
    
    public void setSfbcsj(String sfbcsj) {
        this.sfbcsj = sfbcsj;
    }
    public String getZrks() {
        return this.zrks;
    }
    
    public void setZrks(String zrks) {
        this.zrks = zrks;
    }
    public String getZrr() {
        return this.zrr;
    }
    
    public void setZrr(String zrr) {
        this.zrr = zrr;
    }
    public String getYxj() {
        return this.yxj;
    }
    
    public void setYxj(String yxj) {
        this.yxj = yxj;
    }
    public String getSjbz() {
        return this.sjbz;
    }
    
    public void setSjbz(String sjbz) {
        this.sjbz = sjbz;
    }
    public String getBcsm() {
        return this.bcsm;
    }
    
    public void setBcsm(String bcsm) {
        this.bcsm = bcsm;
    }
    public String getFcslh() {
        return this.fcslh;
    }
    
    public void setFcslh(String fcslh) {
        this.fcslh = fcslh;
    }
    public String getFcdjlx() {
        return this.fcdjlx;
    }
    
    public void setFcdjlx(String fcdjlx) {
        this.fcdjlx = fcdjlx;
    }
    public String getFchid() {
        return this.fchid;
    }
    
    public void setFchid(String fchid) {
        this.fchid = fchid;
    }
    public String getBizmsgid() {
        return this.bizmsgid;
    }
    
    public void setBizmsgid(String bizmsgid) {
        this.bizmsgid = bizmsgid;
    }
    public String getJrywbm() {
        return this.jrywbm;
    }
    
    public void setJrywbm(String jrywbm) {
        this.jrywbm = jrywbm;
    }
    public BigDecimal getSbzt() {
        return this.sbzt;
    }
    
    public void setSbzt(BigDecimal sbzt) {
        this.sbzt = sbzt;
    }
    public BigDecimal getSbxzcs() {
        return this.sbxzcs;
    }
    
    public void setSbxzcs(BigDecimal sbxzcs) {
        this.sbxzcs = sbxzcs;
    }
    public String getCertinum() {
        return this.certinum;
    }
    
    public void setCertinum(String certinum) {
        this.certinum = certinum;
    }
    public BigDecimal getSbstzt() {
        return this.sbstzt;
    }
    
    public void setSbstzt(BigDecimal sbstzt) {
        this.sbstzt = sbstzt;
    }
    public String getHtbh() {
        return this.htbh;
    }
    
    public void setHtbh(String htbh) {
        this.htbh = htbh;
    }
    public String getPch() {
        return this.pch;
    }
    
    public void setPch(String pch) {
        this.pch = pch;
    }
    public String getJybh() {
        return this.jybh;
    }
    
    public void setJybh(String jybh) {
        this.jybh = jybh;
    }
    public String getAjzt() {
        return this.ajzt;
    }
    
    public void setAjzt(String ajzt) {
        this.ajzt = ajzt;
    }
    public Blob getXczp() {
        return this.xczp;
    }
    
    public void setXczp(Blob xczp) {
        this.xczp = xczp;
    }
    public String getPrjid() {
        return this.prjid;
    }
    
    public void setPrjid(String prjid) {
        this.prjid = prjid;
    }
    public String getLzqk() {
        return this.lzqk;
    }
    
    public void setLzqk(String lzqk) {
        this.lzqk = lzqk;
    }
    public String getTdzh() {
        return this.tdzh;
    }
    
    public void setTdzh(String tdzh) {
        this.tdzh = tdzh;
    }
    public String getCertiinfo() {
        return this.certiinfo;
    }
    
    public void setCertiinfo(String certiinfo) {
        this.certiinfo = certiinfo;
    }
    public BigDecimal getJhzt() {
        return this.jhzt;
    }
    
    public void setJhzt(BigDecimal jhzt) {
        this.jhzt = jhzt;
    }
    public BigDecimal getSfcf() {
        return this.sfcf;
    }
    
    public void setSfcf(BigDecimal sfcf) {
        this.sfcf = sfcf;
    }
    public String getDlrxm() {
        return this.dlrxm;
    }
    
    public void setDlrxm(String dlrxm) {
        this.dlrxm = dlrxm;
    }
    public String getDlrzjhm() {
        return this.dlrzjhm;
    }
    
    public void setDlrzjhm(String dlrzjhm) {
        this.dlrzjhm = dlrzjhm;
    }
    public String getSharekey() {
        return this.sharekey;
    }
    
    public void setSharekey(String sharekey) {
        this.sharekey = sharekey;
    }
    public Date getSharetime() {
        return this.sharetime;
    }
    
    public void setSharetime(Date sharetime) {
        this.sharetime = sharetime;
    }
    public String getSharestate() {
        return this.sharestate;
    }
    
    public void setSharestate(String sharestate) {
        this.sharestate = sharestate;
    }
    public String getQxkz() {
        return this.qxkz;
    }
    
    public void setQxkz(String qxkz) {
        this.qxkz = qxkz;
    }
    public String getCgzt() {
        return this.cgzt;
    }
    
    public void setCgzt(String cgzt) {
        this.cgzt = cgzt;
    }
    public String getWwsqbh() {
        return this.wwsqbh;
    }
    
    public void setWwsqbh(String wwsqbh) {
        this.wwsqbh = wwsqbh;
    }
    public String getWwyybh() {
        return this.wwyybh;
    }
    
    public void setWwyybh(String wwyybh) {
        this.wwyybh = wwyybh;
    }
    public String getQyxs() {
        return this.qyxs;
    }
    
    public void setQyxs(String qyxs) {
        this.qyxs = qyxs;
    }
    public BigDecimal getZkbs() {
        return this.zkbs;
    }
    
    public void setZkbs(BigDecimal zkbs) {
        this.zkbs = zkbs;
    }
    public Date getSharetimeFc() {
        return this.sharetimeFc;
    }
    
    public void setSharetimeFc(Date sharetimeFc) {
        this.sharetimeFc = sharetimeFc;
    }
    public String getSharestateFc() {
        return this.sharestateFc;
    }
    
    public void setSharestateFc(String sharestateFc) {
        this.sharestateFc = sharestateFc;
    }
    public String getGgXmbh() {
        return this.ggXmbh;
    }
    
    public void setGgXmbh(String ggXmbh) {
        this.ggXmbh = ggXmbh;
    }
    public String getSbjg() {
        return this.sbjg;
    }
    
    public void setSbjg(String sbjg) {
        this.sbjg = sbjg;
    }
    public BigDecimal getSbcs() {
        return this.sbcs;
    }
    
    public void setSbcs(BigDecimal sbcs) {
        this.sbcs = sbcs;
    }
    public Date getSbsj() {
        return this.sbsj;
    }
    
    public void setSbsj(Date sbsj) {
        this.sbsj = sbsj;
    }
    public String getSharestateZw() {
        return this.sharestateZw;
    }
    
    public void setSharestateZw(String sharestateZw) {
        this.sharestateZw = sharestateZw;
    }
    public String getTszt() {
        return this.tszt;
    }
    
    public void setTszt(String tszt) {
        this.tszt = tszt;
    }


	@Override
	public String getIdName() {
		// TODO Auto-generated method stub
		return "slbh";
	}


	@Override
	public String getDataVersionName() {
		// TODO Auto-generated method stub
		return null;
	}




}


