package com.iawtr.database.dto;
// Generated 2019-1-7 14:12:28 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * DjSpb generated by hbm2java
 */
public class DjSpb  implements java.io.Serializable ,DtoInterface {
	private static final long serialVersionUID = 1L;

     private String spbh;
     private String slbh;
     private String spdx;
     private BigDecimal spxh;
     private String spyj;
     private String spr;
     private Date sprq;
     private String sprzgzh;
     private String spjg;
     private String spzt;
     private String appid;
     private String spdx1;
     private String sptxr;

    public DjSpb() {
    }

	
    public DjSpb(String spbh) {
        this.spbh = spbh;
    }
    public DjSpb(String spbh, String slbh, String spdx, BigDecimal spxh, String spyj, String spr, Date sprq, String sprzgzh, String spjg, String spzt, String appid, String spdx1, String sptxr) {
       this.spbh = spbh;
       this.slbh = slbh;
       this.spdx = spdx;
       this.spxh = spxh;
       this.spyj = spyj;
       this.spr = spr;
       this.sprq = sprq;
       this.sprzgzh = sprzgzh;
       this.spjg = spjg;
       this.spzt = spzt;
       this.appid = appid;
       this.spdx1 = spdx1;
       this.sptxr = sptxr;
    }
   
    public String getSpbh() {
        return this.spbh;
    }
    
    public void setSpbh(String spbh) {
        this.spbh = spbh;
    }
    public String getSlbh() {
        return this.slbh;
    }
    
    public void setSlbh(String slbh) {
        this.slbh = slbh;
    }
    public String getSpdx() {
        return this.spdx;
    }
    
    public void setSpdx(String spdx) {
        this.spdx = spdx;
    }
    public BigDecimal getSpxh() {
        return this.spxh;
    }
    
    public void setSpxh(BigDecimal spxh) {
        this.spxh = spxh;
    }
    public String getSpyj() {
        return this.spyj;
    }
    
    public void setSpyj(String spyj) {
        this.spyj = spyj;
    }
    public String getSpr() {
        return this.spr;
    }
    
    public void setSpr(String spr) {
        this.spr = spr;
    }
    public Date getSprq() {
        return this.sprq;
    }
    
    public void setSprq(Date sprq) {
        this.sprq = sprq;
    }
    public String getSprzgzh() {
        return this.sprzgzh;
    }
    
    public void setSprzgzh(String sprzgzh) {
        this.sprzgzh = sprzgzh;
    }
    public String getSpjg() {
        return this.spjg;
    }
    
    public void setSpjg(String spjg) {
        this.spjg = spjg;
    }
    public String getSpzt() {
        return this.spzt;
    }
    
    public void setSpzt(String spzt) {
        this.spzt = spzt;
    }
    public String getAppid() {
        return this.appid;
    }
    
    public void setAppid(String appid) {
        this.appid = appid;
    }
    public String getSpdx1() {
        return this.spdx1;
    }
    
    public void setSpdx1(String spdx1) {
        this.spdx1 = spdx1;
    }
    public String getSptxr() {
        return this.sptxr;
    }
    
    public void setSptxr(String sptxr) {
        this.sptxr = sptxr;
    }


	@Override
	public String getIdName() {
		// TODO Auto-generated method stub
		return "spbh";
	}


	@Override
	public String getDataVersionName() {
		// TODO Auto-generated method stub
		return null;
	}




}


