package com.iawtr.database.dto;
// Generated 2019-1-7 14:12:28 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * DjTsgl generated by hbm2java
 */
public class DjTsgl  implements java.io.Serializable ,DtoInterface {
	private static final long serialVersionUID = 1L;

     private String glbm;
     private String slbh;
     private String bdclx;
     private String tstybm;
     private String bdcdyh;
     private String djzl;
     private String glms;
     private Date cssj;
     private BigDecimal lifecycle;
     private String ytstybm;
     private String zl;
     private String qlxz;
     private String qllx;
     private String syqx;
     private BigDecimal jzmj;
     private String yslbh;
     private BigDecimal lifecycle1;
     private BigDecimal flag;
     private String yslbh1;
     private BigDecimal sfcf;
     private String zl1;
     private BigDecimal tnjzmj;
     private BigDecimal ftjzmj;
     private Date xsqsrq;
     private Date xsjzrq;
     private String tstybm1;
     private String regid;
     private String ybdcdyh;

    public DjTsgl() {
    }

	
    public DjTsgl(String glbm) {
        this.glbm = glbm;
    }
    public DjTsgl(String glbm, String slbh, String bdclx, String tstybm, String bdcdyh, String djzl, String glms, Date cssj, BigDecimal lifecycle, String ytstybm, String zl, String qlxz, String qllx, String syqx, BigDecimal jzmj, String yslbh, BigDecimal lifecycle1, BigDecimal flag, String yslbh1, BigDecimal sfcf, String zl1, BigDecimal tnjzmj, BigDecimal ftjzmj, Date xsqsrq, Date xsjzrq, String tstybm1, String regid, String ybdcdyh) {
       this.glbm = glbm;
       this.slbh = slbh;
       this.bdclx = bdclx;
       this.tstybm = tstybm;
       this.bdcdyh = bdcdyh;
       this.djzl = djzl;
       this.glms = glms;
       this.cssj = cssj;
       this.lifecycle = lifecycle;
       this.ytstybm = ytstybm;
       this.zl = zl;
       this.qlxz = qlxz;
       this.qllx = qllx;
       this.syqx = syqx;
       this.jzmj = jzmj;
       this.yslbh = yslbh;
       this.lifecycle1 = lifecycle1;
       this.flag = flag;
       this.yslbh1 = yslbh1;
       this.sfcf = sfcf;
       this.zl1 = zl1;
       this.tnjzmj = tnjzmj;
       this.ftjzmj = ftjzmj;
       this.xsqsrq = xsqsrq;
       this.xsjzrq = xsjzrq;
       this.tstybm1 = tstybm1;
       this.regid = regid;
       this.ybdcdyh = ybdcdyh;
    }
   
    public String getGlbm() {
        return this.glbm;
    }
    
    public void setGlbm(String glbm) {
        this.glbm = glbm;
    }
    public String getSlbh() {
        return this.slbh;
    }
    
    public void setSlbh(String slbh) {
        this.slbh = slbh;
    }
    public String getBdclx() {
        return this.bdclx;
    }
    
    public void setBdclx(String bdclx) {
        this.bdclx = bdclx;
    }
    public String getTstybm() {
        return this.tstybm;
    }
    
    public void setTstybm(String tstybm) {
        this.tstybm = tstybm;
    }
    public String getBdcdyh() {
        return this.bdcdyh;
    }
    
    public void setBdcdyh(String bdcdyh) {
        this.bdcdyh = bdcdyh;
    }
    public String getDjzl() {
        return this.djzl;
    }
    
    public void setDjzl(String djzl) {
        this.djzl = djzl;
    }
    public String getGlms() {
        return this.glms;
    }
    
    public void setGlms(String glms) {
        this.glms = glms;
    }
    public Date getCssj() {
        return this.cssj;
    }
    
    public void setCssj(Date cssj) {
        this.cssj = cssj;
    }
    public BigDecimal getLifecycle() {
        return this.lifecycle;
    }
    
    public void setLifecycle(BigDecimal lifecycle) {
        this.lifecycle = lifecycle;
    }
    public String getYtstybm() {
        return this.ytstybm;
    }
    
    public void setYtstybm(String ytstybm) {
        this.ytstybm = ytstybm;
    }
    public String getZl() {
        return this.zl;
    }
    
    public void setZl(String zl) {
        this.zl = zl;
    }
    public String getQlxz() {
        return this.qlxz;
    }
    
    public void setQlxz(String qlxz) {
        this.qlxz = qlxz;
    }
    public String getQllx() {
        return this.qllx;
    }
    
    public void setQllx(String qllx) {
        this.qllx = qllx;
    }
    public String getSyqx() {
        return this.syqx;
    }
    
    public void setSyqx(String syqx) {
        this.syqx = syqx;
    }
    public BigDecimal getJzmj() {
        return this.jzmj;
    }
    
    public void setJzmj(BigDecimal jzmj) {
        this.jzmj = jzmj;
    }
    public String getYslbh() {
        return this.yslbh;
    }
    
    public void setYslbh(String yslbh) {
        this.yslbh = yslbh;
    }
    public BigDecimal getLifecycle1() {
        return this.lifecycle1;
    }
    
    public void setLifecycle1(BigDecimal lifecycle1) {
        this.lifecycle1 = lifecycle1;
    }
    public BigDecimal getFlag() {
        return this.flag;
    }
    
    public void setFlag(BigDecimal flag) {
        this.flag = flag;
    }
    public String getYslbh1() {
        return this.yslbh1;
    }
    
    public void setYslbh1(String yslbh1) {
        this.yslbh1 = yslbh1;
    }
    public BigDecimal getSfcf() {
        return this.sfcf;
    }
    
    public void setSfcf(BigDecimal sfcf) {
        this.sfcf = sfcf;
    }
    public String getZl1() {
        return this.zl1;
    }
    
    public void setZl1(String zl1) {
        this.zl1 = zl1;
    }
    public BigDecimal getTnjzmj() {
        return this.tnjzmj;
    }
    
    public void setTnjzmj(BigDecimal tnjzmj) {
        this.tnjzmj = tnjzmj;
    }
    public BigDecimal getFtjzmj() {
        return this.ftjzmj;
    }
    
    public void setFtjzmj(BigDecimal ftjzmj) {
        this.ftjzmj = ftjzmj;
    }
    public Date getXsqsrq() {
        return this.xsqsrq;
    }
    
    public void setXsqsrq(Date xsqsrq) {
        this.xsqsrq = xsqsrq;
    }
    public Date getXsjzrq() {
        return this.xsjzrq;
    }
    
    public void setXsjzrq(Date xsjzrq) {
        this.xsjzrq = xsjzrq;
    }
    public String getTstybm1() {
        return this.tstybm1;
    }
    
    public void setTstybm1(String tstybm1) {
        this.tstybm1 = tstybm1;
    }
    public String getRegid() {
        return this.regid;
    }
    
    public void setRegid(String regid) {
        this.regid = regid;
    }
    public String getYbdcdyh() {
        return this.ybdcdyh;
    }
    
    public void setYbdcdyh(String ybdcdyh) {
        this.ybdcdyh = ybdcdyh;
    }


	@Override
	public String getIdName() {
		// TODO Auto-generated method stub
		return "glbm";
	}


	@Override
	public String getDataVersionName() {
		// TODO Auto-generated method stub
		return null;
	}




}


