package com.iawtr.database.dto;
// Generated 2019-1-7 14:12:28 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * DjYy generated by hbm2java
 */
public class DjYy  implements java.io.Serializable ,DtoInterface {
	private static final long serialVersionUID = 1L;

     private String slbh;
     private String xgzh;
     private String bdcdyh;
     private String yysx;
     private String sqr;
     private String jbr;
     private Date jbrq;
     private String bdczmh;
     private String ssjc;
     private String jgjc;
     private String fznd;
     private String zsh;
     private String fzjg;
     private Date fzrq;
     private String zsxlh;
     private BigDecimal dycs;
     private String gdh;
     private String damj;
     private String qt;
     private String fj;
     private String hdpch;
     private String szpch;
     private BigDecimal lifecycle;
     private String szr;
     private Date djrq;
     private String dbr;
     private String spbz;
     private String djyy;
     private String wz;
     private String dzzsxlh;
     private String YSlbh;
     private String YFwid;

    public DjYy() {
    }

	
    public DjYy(String slbh) {
        this.slbh = slbh;
    }
    public DjYy(String slbh, String xgzh, String bdcdyh, String yysx, String sqr, String jbr, Date jbrq, String bdczmh, String ssjc, String jgjc, String fznd, String zsh, String fzjg, Date fzrq, String zsxlh, BigDecimal dycs, String gdh, String damj, String qt, String fj, String hdpch, String szpch, BigDecimal lifecycle, String szr, Date djrq, String dbr, String spbz, String djyy, String wz, String dzzsxlh, String YSlbh, String YFwid) {
       this.slbh = slbh;
       this.xgzh = xgzh;
       this.bdcdyh = bdcdyh;
       this.yysx = yysx;
       this.sqr = sqr;
       this.jbr = jbr;
       this.jbrq = jbrq;
       this.bdczmh = bdczmh;
       this.ssjc = ssjc;
       this.jgjc = jgjc;
       this.fznd = fznd;
       this.zsh = zsh;
       this.fzjg = fzjg;
       this.fzrq = fzrq;
       this.zsxlh = zsxlh;
       this.dycs = dycs;
       this.gdh = gdh;
       this.damj = damj;
       this.qt = qt;
       this.fj = fj;
       this.hdpch = hdpch;
       this.szpch = szpch;
       this.lifecycle = lifecycle;
       this.szr = szr;
       this.djrq = djrq;
       this.dbr = dbr;
       this.spbz = spbz;
       this.djyy = djyy;
       this.wz = wz;
       this.dzzsxlh = dzzsxlh;
       this.YSlbh = YSlbh;
       this.YFwid = YFwid;
    }
   
    public String getSlbh() {
        return this.slbh;
    }
    
    public void setSlbh(String slbh) {
        this.slbh = slbh;
    }
    public String getXgzh() {
        return this.xgzh;
    }
    
    public void setXgzh(String xgzh) {
        this.xgzh = xgzh;
    }
    public String getBdcdyh() {
        return this.bdcdyh;
    }
    
    public void setBdcdyh(String bdcdyh) {
        this.bdcdyh = bdcdyh;
    }
    public String getYysx() {
        return this.yysx;
    }
    
    public void setYysx(String yysx) {
        this.yysx = yysx;
    }
    public String getSqr() {
        return this.sqr;
    }
    
    public void setSqr(String sqr) {
        this.sqr = sqr;
    }
    public String getJbr() {
        return this.jbr;
    }
    
    public void setJbr(String jbr) {
        this.jbr = jbr;
    }
    public Date getJbrq() {
        return this.jbrq;
    }
    
    public void setJbrq(Date jbrq) {
        this.jbrq = jbrq;
    }
    public String getBdczmh() {
        return this.bdczmh;
    }
    
    public void setBdczmh(String bdczmh) {
        this.bdczmh = bdczmh;
    }
    public String getSsjc() {
        return this.ssjc;
    }
    
    public void setSsjc(String ssjc) {
        this.ssjc = ssjc;
    }
    public String getJgjc() {
        return this.jgjc;
    }
    
    public void setJgjc(String jgjc) {
        this.jgjc = jgjc;
    }
    public String getFznd() {
        return this.fznd;
    }
    
    public void setFznd(String fznd) {
        this.fznd = fznd;
    }
    public String getZsh() {
        return this.zsh;
    }
    
    public void setZsh(String zsh) {
        this.zsh = zsh;
    }
    public String getFzjg() {
        return this.fzjg;
    }
    
    public void setFzjg(String fzjg) {
        this.fzjg = fzjg;
    }
    public Date getFzrq() {
        return this.fzrq;
    }
    
    public void setFzrq(Date fzrq) {
        this.fzrq = fzrq;
    }
    public String getZsxlh() {
        return this.zsxlh;
    }
    
    public void setZsxlh(String zsxlh) {
        this.zsxlh = zsxlh;
    }
    public BigDecimal getDycs() {
        return this.dycs;
    }
    
    public void setDycs(BigDecimal dycs) {
        this.dycs = dycs;
    }
    public String getGdh() {
        return this.gdh;
    }
    
    public void setGdh(String gdh) {
        this.gdh = gdh;
    }
    public String getDamj() {
        return this.damj;
    }
    
    public void setDamj(String damj) {
        this.damj = damj;
    }
    public String getQt() {
        return this.qt;
    }
    
    public void setQt(String qt) {
        this.qt = qt;
    }
    public String getFj() {
        return this.fj;
    }
    
    public void setFj(String fj) {
        this.fj = fj;
    }
    public String getHdpch() {
        return this.hdpch;
    }
    
    public void setHdpch(String hdpch) {
        this.hdpch = hdpch;
    }
    public String getSzpch() {
        return this.szpch;
    }
    
    public void setSzpch(String szpch) {
        this.szpch = szpch;
    }
    public BigDecimal getLifecycle() {
        return this.lifecycle;
    }
    
    public void setLifecycle(BigDecimal lifecycle) {
        this.lifecycle = lifecycle;
    }
    public String getSzr() {
        return this.szr;
    }
    
    public void setSzr(String szr) {
        this.szr = szr;
    }
    public Date getDjrq() {
        return this.djrq;
    }
    
    public void setDjrq(Date djrq) {
        this.djrq = djrq;
    }
    public String getDbr() {
        return this.dbr;
    }
    
    public void setDbr(String dbr) {
        this.dbr = dbr;
    }
    public String getSpbz() {
        return this.spbz;
    }
    
    public void setSpbz(String spbz) {
        this.spbz = spbz;
    }
    public String getDjyy() {
        return this.djyy;
    }
    
    public void setDjyy(String djyy) {
        this.djyy = djyy;
    }
    public String getWz() {
        return this.wz;
    }
    
    public void setWz(String wz) {
        this.wz = wz;
    }
    public String getDzzsxlh() {
        return this.dzzsxlh;
    }
    
    public void setDzzsxlh(String dzzsxlh) {
        this.dzzsxlh = dzzsxlh;
    }
    public String getYSlbh() {
        return this.YSlbh;
    }
    
    public void setYSlbh(String YSlbh) {
        this.YSlbh = YSlbh;
    }
    public String getYFwid() {
        return this.YFwid;
    }
    
    public void setYFwid(String YFwid) {
        this.YFwid = YFwid;
    }


	@Override
	public String getIdName() {
		// TODO Auto-generated method stub
		return "slbh";
	}


	@Override
	public String getDataVersionName() {
		// TODO Auto-generated method stub
		return null;
	}




}


