package com.iawtr.database.dto;
// Generated 2019-1-7 14:12:28 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;

/**
 * FcHQsdc generated by hbm2java
 */
public class FcHQsdc  implements java.io.Serializable ,DtoInterface {
	private static final long serialVersionUID = 1L;

     private String tstybm;
     private String zdtybm;
     private String zh;
     private String hh;
     private String bdcdyh;
     private String lsztybm;
     private String lsfwbh;
     private String qllx;
     private String qlxz;
     private String hx;
     private String hxjg;
     private String zxcd;
     private String ghyt;
     private String zl;
     private BigDecimal sjc;
     private String myc;
     private String dyh;
     private String fjh;
     private String ljzh;
     private BigDecimal qdjg;
     private String qdfs;
     private String shbw;
     private BigDecimal ycjzmj;
     private BigDecimal yctnjzmj;
     private BigDecimal ycdxbfjzmj;
     private BigDecimal ycftjzmj;
     private BigDecimal ycqtjzmj;
     private BigDecimal ycftxs;
     private BigDecimal jzmj;
     private BigDecimal tnjzmj;
     private BigDecimal ftjzmj;
     private BigDecimal dxbfjzmj;
     private BigDecimal qtjzmj;
     private BigDecimal ftxs;
     private Date tdzzrq;
     private String tdyt;
     private String tdsyqr;
     private BigDecimal gytdmj;
     private BigDecimal fttdmj;
     private BigDecimal dytdmj;
     private String fwlx;
     private String fwxz;
     private BigDecimal sjcs;
     private BigDecimal tcjs;
     private BigDecimal cg;
     private BigDecimal zt;
     private Blob fcfht;
     private Blob fcfhct;
     private String dcz;
     private Date dcsj;
     private String dcyj;
     private String fjsm;
     private BigDecimal sjclh;
     private String oldbdcdyh;
     private BigDecimal lifecycle;
     private String dymc;
     private String tdsyqx;
     private Date tdqsrq;
     private String tdqlxz;
     private BigDecimal xccjmj;
     private BigDecimal gccjmj;
     private String wznf;
     private BigDecimal wzjzmj;
     private String fjzb;
     private BigDecimal zbtop;
     private BigDecimal zbleft;
     private BigDecimal zbright;
     private BigDecimal zbbottom;
     private String hlx;
     private String chzt;
     private String zid;
     private String zl1;
     private String lsztybm1;
     private String bdcdyh1;
     private String dxs;
     private BigDecimal dxsmj;
     private String cfbz;
     private BigDecimal bsm;
     private String csbsm;
     private String xwbsm;
     private String gl;
     private String yhbh;
     private String sharestate;
     private String bgjzxx;
     private String bgtsxx;
     private String isrghs;
     private String rghsry;
     private Date rghsrq;
     private String csyj;
     private String csr;
     private Date csrq;
     private String fsyj;
     private String fsr;
     private Date fsrq;
     private String zsyj;
     private String zsr;
     private Date zsrq;
     private String yhid;
     private String qtd;
     private String qtn;
     private String qtx;
     private String qtb;
     private String gzwlx;
     private Date sharetime;
     private BigDecimal hdj;
     private String houseid;
     private String sjly;
     private String ghytms;
     private BigDecimal zdmj;
     private String lsbdcdyh;
     private String cb;
     private String tdzh;
     private String yzid;
     private String regid;
     private String sharestateFc;

    public FcHQsdc() {
    }

	
    public FcHQsdc(String tstybm) {
        this.tstybm = tstybm;
    }
    public FcHQsdc(String tstybm, String zdtybm, String zh, String hh, String bdcdyh, String lsztybm, String lsfwbh, String qllx, String qlxz, String hx, String hxjg, String zxcd, String ghyt, String zl, BigDecimal sjc, String myc, String dyh, String fjh, String ljzh, BigDecimal qdjg, String qdfs, String shbw, BigDecimal ycjzmj, BigDecimal yctnjzmj, BigDecimal ycdxbfjzmj, BigDecimal ycftjzmj, BigDecimal ycqtjzmj, BigDecimal ycftxs, BigDecimal jzmj, BigDecimal tnjzmj, BigDecimal ftjzmj, BigDecimal dxbfjzmj, BigDecimal qtjzmj, BigDecimal ftxs, Date tdzzrq, String tdyt, String tdsyqr, BigDecimal gytdmj, BigDecimal fttdmj, BigDecimal dytdmj, String fwlx, String fwxz, BigDecimal sjcs, BigDecimal tcjs, BigDecimal cg, BigDecimal zt, Blob fcfht, Blob fcfhct, String dcz, Date dcsj, String dcyj, String fjsm, BigDecimal sjclh, String oldbdcdyh, BigDecimal lifecycle, String dymc, String tdsyqx, Date tdqsrq, String tdqlxz, BigDecimal xccjmj, BigDecimal gccjmj, String wznf, BigDecimal wzjzmj, String fjzb, BigDecimal zbtop, BigDecimal zbleft, BigDecimal zbright, BigDecimal zbbottom, String hlx, String chzt, String zid, String zl1, String lsztybm1, String bdcdyh1, String dxs, BigDecimal dxsmj, String cfbz, BigDecimal bsm, String csbsm, String xwbsm, String gl, String yhbh, String sharestate, String bgjzxx, String bgtsxx, String isrghs, String rghsry, Date rghsrq, String csyj, String csr, Date csrq, String fsyj, String fsr, Date fsrq, String zsyj, String zsr, Date zsrq, String yhid, String qtd, String qtn, String qtx, String qtb, String gzwlx, Date sharetime, BigDecimal hdj, String houseid, String sjly, String ghytms, BigDecimal zdmj, String lsbdcdyh, String cb, String tdzh, String yzid, String regid, String sharestateFc) {
       this.tstybm = tstybm;
       this.zdtybm = zdtybm;
       this.zh = zh;
       this.hh = hh;
       this.bdcdyh = bdcdyh;
       this.lsztybm = lsztybm;
       this.lsfwbh = lsfwbh;
       this.qllx = qllx;
       this.qlxz = qlxz;
       this.hx = hx;
       this.hxjg = hxjg;
       this.zxcd = zxcd;
       this.ghyt = ghyt;
       this.zl = zl;
       this.sjc = sjc;
       this.myc = myc;
       this.dyh = dyh;
       this.fjh = fjh;
       this.ljzh = ljzh;
       this.qdjg = qdjg;
       this.qdfs = qdfs;
       this.shbw = shbw;
       this.ycjzmj = ycjzmj;
       this.yctnjzmj = yctnjzmj;
       this.ycdxbfjzmj = ycdxbfjzmj;
       this.ycftjzmj = ycftjzmj;
       this.ycqtjzmj = ycqtjzmj;
       this.ycftxs = ycftxs;
       this.jzmj = jzmj;
       this.tnjzmj = tnjzmj;
       this.ftjzmj = ftjzmj;
       this.dxbfjzmj = dxbfjzmj;
       this.qtjzmj = qtjzmj;
       this.ftxs = ftxs;
       this.tdzzrq = tdzzrq;
       this.tdyt = tdyt;
       this.tdsyqr = tdsyqr;
       this.gytdmj = gytdmj;
       this.fttdmj = fttdmj;
       this.dytdmj = dytdmj;
       this.fwlx = fwlx;
       this.fwxz = fwxz;
       this.sjcs = sjcs;
       this.tcjs = tcjs;
       this.cg = cg;
       this.zt = zt;
       this.fcfht = fcfht;
       this.fcfhct = fcfhct;
       this.dcz = dcz;
       this.dcsj = dcsj;
       this.dcyj = dcyj;
       this.fjsm = fjsm;
       this.sjclh = sjclh;
       this.oldbdcdyh = oldbdcdyh;
       this.lifecycle = lifecycle;
       this.dymc = dymc;
       this.tdsyqx = tdsyqx;
       this.tdqsrq = tdqsrq;
       this.tdqlxz = tdqlxz;
       this.xccjmj = xccjmj;
       this.gccjmj = gccjmj;
       this.wznf = wznf;
       this.wzjzmj = wzjzmj;
       this.fjzb = fjzb;
       this.zbtop = zbtop;
       this.zbleft = zbleft;
       this.zbright = zbright;
       this.zbbottom = zbbottom;
       this.hlx = hlx;
       this.chzt = chzt;
       this.zid = zid;
       this.zl1 = zl1;
       this.lsztybm1 = lsztybm1;
       this.bdcdyh1 = bdcdyh1;
       this.dxs = dxs;
       this.dxsmj = dxsmj;
       this.cfbz = cfbz;
       this.bsm = bsm;
       this.csbsm = csbsm;
       this.xwbsm = xwbsm;
       this.gl = gl;
       this.yhbh = yhbh;
       this.sharestate = sharestate;
       this.bgjzxx = bgjzxx;
       this.bgtsxx = bgtsxx;
       this.isrghs = isrghs;
       this.rghsry = rghsry;
       this.rghsrq = rghsrq;
       this.csyj = csyj;
       this.csr = csr;
       this.csrq = csrq;
       this.fsyj = fsyj;
       this.fsr = fsr;
       this.fsrq = fsrq;
       this.zsyj = zsyj;
       this.zsr = zsr;
       this.zsrq = zsrq;
       this.yhid = yhid;
       this.qtd = qtd;
       this.qtn = qtn;
       this.qtx = qtx;
       this.qtb = qtb;
       this.gzwlx = gzwlx;
       this.sharetime = sharetime;
       this.hdj = hdj;
       this.houseid = houseid;
       this.sjly = sjly;
       this.ghytms = ghytms;
       this.zdmj = zdmj;
       this.lsbdcdyh = lsbdcdyh;
       this.cb = cb;
       this.tdzh = tdzh;
       this.yzid = yzid;
       this.regid = regid;
       this.sharestateFc = sharestateFc;
    }
   
    public String getTstybm() {
        return this.tstybm;
    }
    
    public void setTstybm(String tstybm) {
        this.tstybm = tstybm;
    }
    public String getZdtybm() {
        return this.zdtybm;
    }
    
    public void setZdtybm(String zdtybm) {
        this.zdtybm = zdtybm;
    }
    public String getZh() {
        return this.zh;
    }
    
    public void setZh(String zh) {
        this.zh = zh;
    }
    public String getHh() {
        return this.hh;
    }
    
    public void setHh(String hh) {
        this.hh = hh;
    }
    public String getBdcdyh() {
        return this.bdcdyh;
    }
    
    public void setBdcdyh(String bdcdyh) {
        this.bdcdyh = bdcdyh;
    }
    public String getLsztybm() {
        return this.lsztybm;
    }
    
    public void setLsztybm(String lsztybm) {
        this.lsztybm = lsztybm;
    }
    public String getLsfwbh() {
        return this.lsfwbh;
    }
    
    public void setLsfwbh(String lsfwbh) {
        this.lsfwbh = lsfwbh;
    }
    public String getQllx() {
        return this.qllx;
    }
    
    public void setQllx(String qllx) {
        this.qllx = qllx;
    }
    public String getQlxz() {
        return this.qlxz;
    }
    
    public void setQlxz(String qlxz) {
        this.qlxz = qlxz;
    }
    public String getHx() {
        return this.hx;
    }
    
    public void setHx(String hx) {
        this.hx = hx;
    }
    public String getHxjg() {
        return this.hxjg;
    }
    
    public void setHxjg(String hxjg) {
        this.hxjg = hxjg;
    }
    public String getZxcd() {
        return this.zxcd;
    }
    
    public void setZxcd(String zxcd) {
        this.zxcd = zxcd;
    }
    public String getGhyt() {
        return this.ghyt;
    }
    
    public void setGhyt(String ghyt) {
        this.ghyt = ghyt;
    }
    public String getZl() {
        return this.zl;
    }
    
    public void setZl(String zl) {
        this.zl = zl;
    }
    public BigDecimal getSjc() {
        return this.sjc;
    }
    
    public void setSjc(BigDecimal sjc) {
        this.sjc = sjc;
    }
    public String getMyc() {
        return this.myc;
    }
    
    public void setMyc(String myc) {
        this.myc = myc;
    }
    public String getDyh() {
        return this.dyh;
    }
    
    public void setDyh(String dyh) {
        this.dyh = dyh;
    }
    public String getFjh() {
        return this.fjh;
    }
    
    public void setFjh(String fjh) {
        this.fjh = fjh;
    }
    public String getLjzh() {
        return this.ljzh;
    }
    
    public void setLjzh(String ljzh) {
        this.ljzh = ljzh;
    }
    public BigDecimal getQdjg() {
        return this.qdjg;
    }
    
    public void setQdjg(BigDecimal qdjg) {
        this.qdjg = qdjg;
    }
    public String getQdfs() {
        return this.qdfs;
    }
    
    public void setQdfs(String qdfs) {
        this.qdfs = qdfs;
    }
    public String getShbw() {
        return this.shbw;
    }
    
    public void setShbw(String shbw) {
        this.shbw = shbw;
    }
    public BigDecimal getYcjzmj() {
        return this.ycjzmj;
    }
    
    public void setYcjzmj(BigDecimal ycjzmj) {
        this.ycjzmj = ycjzmj;
    }
    public BigDecimal getYctnjzmj() {
        return this.yctnjzmj;
    }
    
    public void setYctnjzmj(BigDecimal yctnjzmj) {
        this.yctnjzmj = yctnjzmj;
    }
    public BigDecimal getYcdxbfjzmj() {
        return this.ycdxbfjzmj;
    }
    
    public void setYcdxbfjzmj(BigDecimal ycdxbfjzmj) {
        this.ycdxbfjzmj = ycdxbfjzmj;
    }
    public BigDecimal getYcftjzmj() {
        return this.ycftjzmj;
    }
    
    public void setYcftjzmj(BigDecimal ycftjzmj) {
        this.ycftjzmj = ycftjzmj;
    }
    public BigDecimal getYcqtjzmj() {
        return this.ycqtjzmj;
    }
    
    public void setYcqtjzmj(BigDecimal ycqtjzmj) {
        this.ycqtjzmj = ycqtjzmj;
    }
    public BigDecimal getYcftxs() {
        return this.ycftxs;
    }
    
    public void setYcftxs(BigDecimal ycftxs) {
        this.ycftxs = ycftxs;
    }
    public BigDecimal getJzmj() {
        return this.jzmj;
    }
    
    public void setJzmj(BigDecimal jzmj) {
        this.jzmj = jzmj;
    }
    public BigDecimal getTnjzmj() {
        return this.tnjzmj;
    }
    
    public void setTnjzmj(BigDecimal tnjzmj) {
        this.tnjzmj = tnjzmj;
    }
    public BigDecimal getFtjzmj() {
        return this.ftjzmj;
    }
    
    public void setFtjzmj(BigDecimal ftjzmj) {
        this.ftjzmj = ftjzmj;
    }
    public BigDecimal getDxbfjzmj() {
        return this.dxbfjzmj;
    }
    
    public void setDxbfjzmj(BigDecimal dxbfjzmj) {
        this.dxbfjzmj = dxbfjzmj;
    }
    public BigDecimal getQtjzmj() {
        return this.qtjzmj;
    }
    
    public void setQtjzmj(BigDecimal qtjzmj) {
        this.qtjzmj = qtjzmj;
    }
    public BigDecimal getFtxs() {
        return this.ftxs;
    }
    
    public void setFtxs(BigDecimal ftxs) {
        this.ftxs = ftxs;
    }
    public Date getTdzzrq() {
        return this.tdzzrq;
    }
    
    public void setTdzzrq(Date tdzzrq) {
        this.tdzzrq = tdzzrq;
    }
    public String getTdyt() {
        return this.tdyt;
    }
    
    public void setTdyt(String tdyt) {
        this.tdyt = tdyt;
    }
    public String getTdsyqr() {
        return this.tdsyqr;
    }
    
    public void setTdsyqr(String tdsyqr) {
        this.tdsyqr = tdsyqr;
    }
    public BigDecimal getGytdmj() {
        return this.gytdmj;
    }
    
    public void setGytdmj(BigDecimal gytdmj) {
        this.gytdmj = gytdmj;
    }
    public BigDecimal getFttdmj() {
        return this.fttdmj;
    }
    
    public void setFttdmj(BigDecimal fttdmj) {
        this.fttdmj = fttdmj;
    }
    public BigDecimal getDytdmj() {
        return this.dytdmj;
    }
    
    public void setDytdmj(BigDecimal dytdmj) {
        this.dytdmj = dytdmj;
    }
    public String getFwlx() {
        return this.fwlx;
    }
    
    public void setFwlx(String fwlx) {
        this.fwlx = fwlx;
    }
    public String getFwxz() {
        return this.fwxz;
    }
    
    public void setFwxz(String fwxz) {
        this.fwxz = fwxz;
    }
    public BigDecimal getSjcs() {
        return this.sjcs;
    }
    
    public void setSjcs(BigDecimal sjcs) {
        this.sjcs = sjcs;
    }
    public BigDecimal getTcjs() {
        return this.tcjs;
    }
    
    public void setTcjs(BigDecimal tcjs) {
        this.tcjs = tcjs;
    }
    public BigDecimal getCg() {
        return this.cg;
    }
    
    public void setCg(BigDecimal cg) {
        this.cg = cg;
    }
    public BigDecimal getZt() {
        return this.zt;
    }
    
    public void setZt(BigDecimal zt) {
        this.zt = zt;
    }
    public Blob getFcfht() {
        return this.fcfht;
    }
    
    public void setFcfht(Blob fcfht) {
        this.fcfht = fcfht;
    }
    public Blob getFcfhct() {
        return this.fcfhct;
    }
    
    public void setFcfhct(Blob fcfhct) {
        this.fcfhct = fcfhct;
    }
    public String getDcz() {
        return this.dcz;
    }
    
    public void setDcz(String dcz) {
        this.dcz = dcz;
    }
    public Date getDcsj() {
        return this.dcsj;
    }
    
    public void setDcsj(Date dcsj) {
        this.dcsj = dcsj;
    }
    public String getDcyj() {
        return this.dcyj;
    }
    
    public void setDcyj(String dcyj) {
        this.dcyj = dcyj;
    }
    public String getFjsm() {
        return this.fjsm;
    }
    
    public void setFjsm(String fjsm) {
        this.fjsm = fjsm;
    }
    public BigDecimal getSjclh() {
        return this.sjclh;
    }
    
    public void setSjclh(BigDecimal sjclh) {
        this.sjclh = sjclh;
    }
    public String getOldbdcdyh() {
        return this.oldbdcdyh;
    }
    
    public void setOldbdcdyh(String oldbdcdyh) {
        this.oldbdcdyh = oldbdcdyh;
    }
    public BigDecimal getLifecycle() {
        return this.lifecycle;
    }
    
    public void setLifecycle(BigDecimal lifecycle) {
        this.lifecycle = lifecycle;
    }
    public String getDymc() {
        return this.dymc;
    }
    
    public void setDymc(String dymc) {
        this.dymc = dymc;
    }
    public String getTdsyqx() {
        return this.tdsyqx;
    }
    
    public void setTdsyqx(String tdsyqx) {
        this.tdsyqx = tdsyqx;
    }
    public Date getTdqsrq() {
        return this.tdqsrq;
    }
    
    public void setTdqsrq(Date tdqsrq) {
        this.tdqsrq = tdqsrq;
    }
    public String getTdqlxz() {
        return this.tdqlxz;
    }
    
    public void setTdqlxz(String tdqlxz) {
        this.tdqlxz = tdqlxz;
    }
    public BigDecimal getXccjmj() {
        return this.xccjmj;
    }
    
    public void setXccjmj(BigDecimal xccjmj) {
        this.xccjmj = xccjmj;
    }
    public BigDecimal getGccjmj() {
        return this.gccjmj;
    }
    
    public void setGccjmj(BigDecimal gccjmj) {
        this.gccjmj = gccjmj;
    }
    public String getWznf() {
        return this.wznf;
    }
    
    public void setWznf(String wznf) {
        this.wznf = wznf;
    }
    public BigDecimal getWzjzmj() {
        return this.wzjzmj;
    }
    
    public void setWzjzmj(BigDecimal wzjzmj) {
        this.wzjzmj = wzjzmj;
    }
    public String getFjzb() {
        return this.fjzb;
    }
    
    public void setFjzb(String fjzb) {
        this.fjzb = fjzb;
    }
    public BigDecimal getZbtop() {
        return this.zbtop;
    }
    
    public void setZbtop(BigDecimal zbtop) {
        this.zbtop = zbtop;
    }
    public BigDecimal getZbleft() {
        return this.zbleft;
    }
    
    public void setZbleft(BigDecimal zbleft) {
        this.zbleft = zbleft;
    }
    public BigDecimal getZbright() {
        return this.zbright;
    }
    
    public void setZbright(BigDecimal zbright) {
        this.zbright = zbright;
    }
    public BigDecimal getZbbottom() {
        return this.zbbottom;
    }
    
    public void setZbbottom(BigDecimal zbbottom) {
        this.zbbottom = zbbottom;
    }
    public String getHlx() {
        return this.hlx;
    }
    
    public void setHlx(String hlx) {
        this.hlx = hlx;
    }
    public String getChzt() {
        return this.chzt;
    }
    
    public void setChzt(String chzt) {
        this.chzt = chzt;
    }
    public String getZid() {
        return this.zid;
    }
    
    public void setZid(String zid) {
        this.zid = zid;
    }
    public String getZl1() {
        return this.zl1;
    }
    
    public void setZl1(String zl1) {
        this.zl1 = zl1;
    }
    public String getLsztybm1() {
        return this.lsztybm1;
    }
    
    public void setLsztybm1(String lsztybm1) {
        this.lsztybm1 = lsztybm1;
    }
    public String getBdcdyh1() {
        return this.bdcdyh1;
    }
    
    public void setBdcdyh1(String bdcdyh1) {
        this.bdcdyh1 = bdcdyh1;
    }
    public String getDxs() {
        return this.dxs;
    }
    
    public void setDxs(String dxs) {
        this.dxs = dxs;
    }
    public BigDecimal getDxsmj() {
        return this.dxsmj;
    }
    
    public void setDxsmj(BigDecimal dxsmj) {
        this.dxsmj = dxsmj;
    }
    public String getCfbz() {
        return this.cfbz;
    }
    
    public void setCfbz(String cfbz) {
        this.cfbz = cfbz;
    }
    public BigDecimal getBsm() {
        return this.bsm;
    }
    
    public void setBsm(BigDecimal bsm) {
        this.bsm = bsm;
    }
    public String getCsbsm() {
        return this.csbsm;
    }
    
    public void setCsbsm(String csbsm) {
        this.csbsm = csbsm;
    }
    public String getXwbsm() {
        return this.xwbsm;
    }
    
    public void setXwbsm(String xwbsm) {
        this.xwbsm = xwbsm;
    }
    public String getGl() {
        return this.gl;
    }
    
    public void setGl(String gl) {
        this.gl = gl;
    }
    public String getYhbh() {
        return this.yhbh;
    }
    
    public void setYhbh(String yhbh) {
        this.yhbh = yhbh;
    }
    public String getSharestate() {
        return this.sharestate;
    }
    
    public void setSharestate(String sharestate) {
        this.sharestate = sharestate;
    }
    public String getBgjzxx() {
        return this.bgjzxx;
    }
    
    public void setBgjzxx(String bgjzxx) {
        this.bgjzxx = bgjzxx;
    }
    public String getBgtsxx() {
        return this.bgtsxx;
    }
    
    public void setBgtsxx(String bgtsxx) {
        this.bgtsxx = bgtsxx;
    }
    public String getIsrghs() {
        return this.isrghs;
    }
    
    public void setIsrghs(String isrghs) {
        this.isrghs = isrghs;
    }
    public String getRghsry() {
        return this.rghsry;
    }
    
    public void setRghsry(String rghsry) {
        this.rghsry = rghsry;
    }
    public Date getRghsrq() {
        return this.rghsrq;
    }
    
    public void setRghsrq(Date rghsrq) {
        this.rghsrq = rghsrq;
    }
    public String getCsyj() {
        return this.csyj;
    }
    
    public void setCsyj(String csyj) {
        this.csyj = csyj;
    }
    public String getCsr() {
        return this.csr;
    }
    
    public void setCsr(String csr) {
        this.csr = csr;
    }
    public Date getCsrq() {
        return this.csrq;
    }
    
    public void setCsrq(Date csrq) {
        this.csrq = csrq;
    }
    public String getFsyj() {
        return this.fsyj;
    }
    
    public void setFsyj(String fsyj) {
        this.fsyj = fsyj;
    }
    public String getFsr() {
        return this.fsr;
    }
    
    public void setFsr(String fsr) {
        this.fsr = fsr;
    }
    public Date getFsrq() {
        return this.fsrq;
    }
    
    public void setFsrq(Date fsrq) {
        this.fsrq = fsrq;
    }
    public String getZsyj() {
        return this.zsyj;
    }
    
    public void setZsyj(String zsyj) {
        this.zsyj = zsyj;
    }
    public String getZsr() {
        return this.zsr;
    }
    
    public void setZsr(String zsr) {
        this.zsr = zsr;
    }
    public Date getZsrq() {
        return this.zsrq;
    }
    
    public void setZsrq(Date zsrq) {
        this.zsrq = zsrq;
    }
    public String getYhid() {
        return this.yhid;
    }
    
    public void setYhid(String yhid) {
        this.yhid = yhid;
    }
    public String getQtd() {
        return this.qtd;
    }
    
    public void setQtd(String qtd) {
        this.qtd = qtd;
    }
    public String getQtn() {
        return this.qtn;
    }
    
    public void setQtn(String qtn) {
        this.qtn = qtn;
    }
    public String getQtx() {
        return this.qtx;
    }
    
    public void setQtx(String qtx) {
        this.qtx = qtx;
    }
    public String getQtb() {
        return this.qtb;
    }
    
    public void setQtb(String qtb) {
        this.qtb = qtb;
    }
    public String getGzwlx() {
        return this.gzwlx;
    }
    
    public void setGzwlx(String gzwlx) {
        this.gzwlx = gzwlx;
    }
    public Date getSharetime() {
        return this.sharetime;
    }
    
    public void setSharetime(Date sharetime) {
        this.sharetime = sharetime;
    }
    public BigDecimal getHdj() {
        return this.hdj;
    }
    
    public void setHdj(BigDecimal hdj) {
        this.hdj = hdj;
    }
    public String getHouseid() {
        return this.houseid;
    }
    
    public void setHouseid(String houseid) {
        this.houseid = houseid;
    }
    public String getSjly() {
        return this.sjly;
    }
    
    public void setSjly(String sjly) {
        this.sjly = sjly;
    }
    public String getGhytms() {
        return this.ghytms;
    }
    
    public void setGhytms(String ghytms) {
        this.ghytms = ghytms;
    }
    public BigDecimal getZdmj() {
        return this.zdmj;
    }
    
    public void setZdmj(BigDecimal zdmj) {
        this.zdmj = zdmj;
    }
    public String getLsbdcdyh() {
        return this.lsbdcdyh;
    }
    
    public void setLsbdcdyh(String lsbdcdyh) {
        this.lsbdcdyh = lsbdcdyh;
    }
    public String getCb() {
        return this.cb;
    }
    
    public void setCb(String cb) {
        this.cb = cb;
    }
    public String getTdzh() {
        return this.tdzh;
    }
    
    public void setTdzh(String tdzh) {
        this.tdzh = tdzh;
    }
    public String getYzid() {
        return this.yzid;
    }
    
    public void setYzid(String yzid) {
        this.yzid = yzid;
    }
    public String getRegid() {
        return this.regid;
    }
    
    public void setRegid(String regid) {
        this.regid = regid;
    }
    public String getSharestateFc() {
        return this.sharestateFc;
    }
    
    public void setSharestateFc(String sharestateFc) {
        this.sharestateFc = sharestateFc;
    }


	@Override
	public String getIdName() {
		// TODO Auto-generated method stub
		return "tstybm";
	}


	@Override
	public String getDataVersionName() {
		// TODO Auto-generated method stub
		return null;
	}




}


