package com.iawtr.database.dto;
// Generated 2019-1-7 14:12:28 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * QlFwxg generated by hbm2java
 */
public class QlFwxg  implements java.io.Serializable ,DtoInterface {
	private static final long serialVersionUID = 1L;

     private String qlbh;
     private String slbh;
     private String qllx;
     private String qlxz;
     private BigDecimal jzmj;
     private BigDecimal tnjzmj;
     private BigDecimal ftjzmj;
     private String qdfs;
     private BigDecimal qdjg;
     private String jzmjms;
     private String ghytms;
     private String qtnrms;
     private BigDecimal xccjmj;
     private BigDecimal gccjmj;
     private String wznf;
     private BigDecimal wzjzmj;
     private String ghyt;
     private String yslbh;
     private String sfcf;
     private BigDecimal pgje;
     private String gzwlx;
     private String jzwlx;

    public QlFwxg() {
    }

	
    public QlFwxg(String qlbh) {
        this.qlbh = qlbh;
    }
    public QlFwxg(String qlbh, String slbh, String qllx, String qlxz, BigDecimal jzmj, BigDecimal tnjzmj, BigDecimal ftjzmj, String qdfs, BigDecimal qdjg, String jzmjms, String ghytms, String qtnrms, BigDecimal xccjmj, BigDecimal gccjmj, String wznf, BigDecimal wzjzmj, String ghyt, String yslbh, String sfcf, BigDecimal pgje, String gzwlx, String jzwlx) {
       this.qlbh = qlbh;
       this.slbh = slbh;
       this.qllx = qllx;
       this.qlxz = qlxz;
       this.jzmj = jzmj;
       this.tnjzmj = tnjzmj;
       this.ftjzmj = ftjzmj;
       this.qdfs = qdfs;
       this.qdjg = qdjg;
       this.jzmjms = jzmjms;
       this.ghytms = ghytms;
       this.qtnrms = qtnrms;
       this.xccjmj = xccjmj;
       this.gccjmj = gccjmj;
       this.wznf = wznf;
       this.wzjzmj = wzjzmj;
       this.ghyt = ghyt;
       this.yslbh = yslbh;
       this.sfcf = sfcf;
       this.pgje = pgje;
       this.gzwlx = gzwlx;
       this.jzwlx = jzwlx;
    }
   
    public String getQlbh() {
        return this.qlbh;
    }
    
    public void setQlbh(String qlbh) {
        this.qlbh = qlbh;
    }
    public String getSlbh() {
        return this.slbh;
    }
    
    public void setSlbh(String slbh) {
        this.slbh = slbh;
    }
    public String getQllx() {
        return this.qllx;
    }
    
    public void setQllx(String qllx) {
        this.qllx = qllx;
    }
    public String getQlxz() {
        return this.qlxz;
    }
    
    public void setQlxz(String qlxz) {
        this.qlxz = qlxz;
    }
    public BigDecimal getJzmj() {
        return this.jzmj;
    }
    
    public void setJzmj(BigDecimal jzmj) {
        this.jzmj = jzmj;
    }
    public BigDecimal getTnjzmj() {
        return this.tnjzmj;
    }
    
    public void setTnjzmj(BigDecimal tnjzmj) {
        this.tnjzmj = tnjzmj;
    }
    public BigDecimal getFtjzmj() {
        return this.ftjzmj;
    }
    
    public void setFtjzmj(BigDecimal ftjzmj) {
        this.ftjzmj = ftjzmj;
    }
    public String getQdfs() {
        return this.qdfs;
    }
    
    public void setQdfs(String qdfs) {
        this.qdfs = qdfs;
    }
    public BigDecimal getQdjg() {
        return this.qdjg;
    }
    
    public void setQdjg(BigDecimal qdjg) {
        this.qdjg = qdjg;
    }
    public String getJzmjms() {
        return this.jzmjms;
    }
    
    public void setJzmjms(String jzmjms) {
        this.jzmjms = jzmjms;
    }
    public String getGhytms() {
        return this.ghytms;
    }
    
    public void setGhytms(String ghytms) {
        this.ghytms = ghytms;
    }
    public String getQtnrms() {
        return this.qtnrms;
    }
    
    public void setQtnrms(String qtnrms) {
        this.qtnrms = qtnrms;
    }
    public BigDecimal getXccjmj() {
        return this.xccjmj;
    }
    
    public void setXccjmj(BigDecimal xccjmj) {
        this.xccjmj = xccjmj;
    }
    public BigDecimal getGccjmj() {
        return this.gccjmj;
    }
    
    public void setGccjmj(BigDecimal gccjmj) {
        this.gccjmj = gccjmj;
    }
    public String getWznf() {
        return this.wznf;
    }
    
    public void setWznf(String wznf) {
        this.wznf = wznf;
    }
    public BigDecimal getWzjzmj() {
        return this.wzjzmj;
    }
    
    public void setWzjzmj(BigDecimal wzjzmj) {
        this.wzjzmj = wzjzmj;
    }
    public String getGhyt() {
        return this.ghyt;
    }
    
    public void setGhyt(String ghyt) {
        this.ghyt = ghyt;
    }
    public String getYslbh() {
        return this.yslbh;
    }
    
    public void setYslbh(String yslbh) {
        this.yslbh = yslbh;
    }
    public String getSfcf() {
        return this.sfcf;
    }
    
    public void setSfcf(String sfcf) {
        this.sfcf = sfcf;
    }
    public BigDecimal getPgje() {
        return this.pgje;
    }
    
    public void setPgje(BigDecimal pgje) {
        this.pgje = pgje;
    }
    public String getGzwlx() {
        return this.gzwlx;
    }
    
    public void setGzwlx(String gzwlx) {
        this.gzwlx = gzwlx;
    }
    public String getJzwlx() {
        return this.jzwlx;
    }
    
    public void setJzwlx(String jzwlx) {
        this.jzwlx = jzwlx;
    }


	@Override
	public String getIdName() {
		// TODO Auto-generated method stub
		return "qlbh";
	}


	@Override
	public String getDataVersionName() {
		// TODO Auto-generated method stub
		return null;
	}




}


