package com.iawtr.database.dto;
// Generated 2019-1-7 14:12:28 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * QlTdxg generated by hbm2java
 */
public class QlTdxg  implements java.io.Serializable ,DtoInterface {
	private static final long serialVersionUID = 1L;

     private String qlbh;
     private String slbh;
     private String qllx;
     private String qlxz;
     private String syqx;
     private Date qsrq;
     private Date zzrq;
     private String tdyt;
     private String tdsyqr;
     private BigDecimal gytdmj;
     private BigDecimal dytdmj;
     private BigDecimal fttdmj;
     private BigDecimal jzzdmj;
     private BigDecimal jzwzdmj;
     private BigDecimal nydmj;
     private BigDecimal gdmj;
     private BigDecimal ldmj;
     private BigDecimal mcdmj;
     private BigDecimal nydqtmj;
     private BigDecimal jsydmj;
     private BigDecimal wlydmj;

    public QlTdxg() {
    }

	
    public QlTdxg(String qlbh) {
        this.qlbh = qlbh;
    }
    public QlTdxg(String qlbh, String slbh, String qllx, String qlxz, String syqx, Date qsrq, Date zzrq, String tdyt, String tdsyqr, BigDecimal gytdmj, BigDecimal dytdmj, BigDecimal fttdmj, BigDecimal jzzdmj, BigDecimal jzwzdmj, BigDecimal nydmj, BigDecimal gdmj, BigDecimal ldmj, BigDecimal mcdmj, BigDecimal nydqtmj, BigDecimal jsydmj, BigDecimal wlydmj) {
       this.qlbh = qlbh;
       this.slbh = slbh;
       this.qllx = qllx;
       this.qlxz = qlxz;
       this.syqx = syqx;
       this.qsrq = qsrq;
       this.zzrq = zzrq;
       this.tdyt = tdyt;
       this.tdsyqr = tdsyqr;
       this.gytdmj = gytdmj;
       this.dytdmj = dytdmj;
       this.fttdmj = fttdmj;
       this.jzzdmj = jzzdmj;
       this.jzwzdmj = jzwzdmj;
       this.nydmj = nydmj;
       this.gdmj = gdmj;
       this.ldmj = ldmj;
       this.mcdmj = mcdmj;
       this.nydqtmj = nydqtmj;
       this.jsydmj = jsydmj;
       this.wlydmj = wlydmj;
    }
   
    public String getQlbh() {
        return this.qlbh;
    }
    
    public void setQlbh(String qlbh) {
        this.qlbh = qlbh;
    }
    public String getSlbh() {
        return this.slbh;
    }
    
    public void setSlbh(String slbh) {
        this.slbh = slbh;
    }
    public String getQllx() {
        return this.qllx;
    }
    
    public void setQllx(String qllx) {
        this.qllx = qllx;
    }
    public String getQlxz() {
        return this.qlxz;
    }
    
    public void setQlxz(String qlxz) {
        this.qlxz = qlxz;
    }
    public String getSyqx() {
        return this.syqx;
    }
    
    public void setSyqx(String syqx) {
        this.syqx = syqx;
    }
    public Date getQsrq() {
        return this.qsrq;
    }
    
    public void setQsrq(Date qsrq) {
        this.qsrq = qsrq;
    }
    public Date getZzrq() {
        return this.zzrq;
    }
    
    public void setZzrq(Date zzrq) {
        this.zzrq = zzrq;
    }
    public String getTdyt() {
        return this.tdyt;
    }
    
    public void setTdyt(String tdyt) {
        this.tdyt = tdyt;
    }
    public String getTdsyqr() {
        return this.tdsyqr;
    }
    
    public void setTdsyqr(String tdsyqr) {
        this.tdsyqr = tdsyqr;
    }
    public BigDecimal getGytdmj() {
        return this.gytdmj;
    }
    
    public void setGytdmj(BigDecimal gytdmj) {
        this.gytdmj = gytdmj;
    }
    public BigDecimal getDytdmj() {
        return this.dytdmj;
    }
    
    public void setDytdmj(BigDecimal dytdmj) {
        this.dytdmj = dytdmj;
    }
    public BigDecimal getFttdmj() {
        return this.fttdmj;
    }
    
    public void setFttdmj(BigDecimal fttdmj) {
        this.fttdmj = fttdmj;
    }
    public BigDecimal getJzzdmj() {
        return this.jzzdmj;
    }
    
    public void setJzzdmj(BigDecimal jzzdmj) {
        this.jzzdmj = jzzdmj;
    }
    public BigDecimal getJzwzdmj() {
        return this.jzwzdmj;
    }
    
    public void setJzwzdmj(BigDecimal jzwzdmj) {
        this.jzwzdmj = jzwzdmj;
    }
    public BigDecimal getNydmj() {
        return this.nydmj;
    }
    
    public void setNydmj(BigDecimal nydmj) {
        this.nydmj = nydmj;
    }
    public BigDecimal getGdmj() {
        return this.gdmj;
    }
    
    public void setGdmj(BigDecimal gdmj) {
        this.gdmj = gdmj;
    }
    public BigDecimal getLdmj() {
        return this.ldmj;
    }
    
    public void setLdmj(BigDecimal ldmj) {
        this.ldmj = ldmj;
    }
    public BigDecimal getMcdmj() {
        return this.mcdmj;
    }
    
    public void setMcdmj(BigDecimal mcdmj) {
        this.mcdmj = mcdmj;
    }
    public BigDecimal getNydqtmj() {
        return this.nydqtmj;
    }
    
    public void setNydqtmj(BigDecimal nydqtmj) {
        this.nydqtmj = nydqtmj;
    }
    public BigDecimal getJsydmj() {
        return this.jsydmj;
    }
    
    public void setJsydmj(BigDecimal jsydmj) {
        this.jsydmj = jsydmj;
    }
    public BigDecimal getWlydmj() {
        return this.wlydmj;
    }
    
    public void setWlydmj(BigDecimal wlydmj) {
        this.wlydmj = wlydmj;
    }


	@Override
	public String getIdName() {
		// TODO Auto-generated method stub
		return "qlbh";
	}


	@Override
	public String getDataVersionName() {
		// TODO Auto-generated method stub
		return null;
	}




}


