package com.iawtr.database.dto;
// Generated 2019-1-7 14:15:31 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * WfmActinst generated by hbm2java
 */
public class WfmActinst  implements java.io.Serializable ,DtoInterface {
	private static final long serialVersionUID = 1L;

     private String wrkid;
     private String prjid;
     private String mdltype;
     private String mdlid;
     private String stepname;
     private String submitby;
     private Date submittime;
     private String acceptby;
     private Date accepttime;
     private Date savetime;
     private String submittype;
     private String transactor;
     private String transactway;
     private Date completetime;
     private String stepstate;
     private String steptype;
     private BigDecimal stepnum;
     private BigDecimal steplimit;
     private Date limittime;
     private String entrypath;
     private String entryparam;
     private String consignor;
     private BigDecimal leftdays;
     private BigDecimal oversee;
     private String biztype;
     private String stepalias;
     private String yjzt;
     private String yjxx;
     private BigDecimal reminds;
     private String unconsent;
     private Date sharetime;
     private String sharestate;
     private String gatestate;
     private String sharestateZw;
     private String sharestateZw1;

    public WfmActinst() {
    }

	
    public WfmActinst(String wrkid, String stepname, Date submittime) {
        this.wrkid = wrkid;
        this.stepname = stepname;
        this.submittime = submittime;
    }
    public WfmActinst(String wrkid, String prjid, String mdltype, String mdlid, String stepname, String submitby, Date submittime, String acceptby, Date accepttime, Date savetime, String submittype, String transactor, String transactway, Date completetime, String stepstate, String steptype, BigDecimal stepnum, BigDecimal steplimit, Date limittime, String entrypath, String entryparam, String consignor, BigDecimal leftdays, BigDecimal oversee, String biztype, String stepalias, String yjzt, String yjxx, BigDecimal reminds, String unconsent, Date sharetime, String sharestate, String gatestate, String sharestateZw, String sharestateZw1) {
       this.wrkid = wrkid;
       this.prjid = prjid;
       this.mdltype = mdltype;
       this.mdlid = mdlid;
       this.stepname = stepname;
       this.submitby = submitby;
       this.submittime = submittime;
       this.acceptby = acceptby;
       this.accepttime = accepttime;
       this.savetime = savetime;
       this.submittype = submittype;
       this.transactor = transactor;
       this.transactway = transactway;
       this.completetime = completetime;
       this.stepstate = stepstate;
       this.steptype = steptype;
       this.stepnum = stepnum;
       this.steplimit = steplimit;
       this.limittime = limittime;
       this.entrypath = entrypath;
       this.entryparam = entryparam;
       this.consignor = consignor;
       this.leftdays = leftdays;
       this.oversee = oversee;
       this.biztype = biztype;
       this.stepalias = stepalias;
       this.yjzt = yjzt;
       this.yjxx = yjxx;
       this.reminds = reminds;
       this.unconsent = unconsent;
       this.sharetime = sharetime;
       this.sharestate = sharestate;
       this.gatestate = gatestate;
       this.sharestateZw = sharestateZw;
       this.sharestateZw1 = sharestateZw1;
    }
   
    public String getWrkid() {
        return this.wrkid;
    }
    
    public void setWrkid(String wrkid) {
        this.wrkid = wrkid;
    }
    public String getPrjid() {
        return this.prjid;
    }
    
    public void setPrjid(String prjid) {
        this.prjid = prjid;
    }
    public String getMdltype() {
        return this.mdltype;
    }
    
    public void setMdltype(String mdltype) {
        this.mdltype = mdltype;
    }
    public String getMdlid() {
        return this.mdlid;
    }
    
    public void setMdlid(String mdlid) {
        this.mdlid = mdlid;
    }
    public String getStepname() {
        return this.stepname;
    }
    
    public void setStepname(String stepname) {
        this.stepname = stepname;
    }
    public String getSubmitby() {
        return this.submitby;
    }
    
    public void setSubmitby(String submitby) {
        this.submitby = submitby;
    }
    public Date getSubmittime() {
        return this.submittime;
    }
    
    public void setSubmittime(Date submittime) {
        this.submittime = submittime;
    }
    public String getAcceptby() {
        return this.acceptby;
    }
    
    public void setAcceptby(String acceptby) {
        this.acceptby = acceptby;
    }
    public Date getAccepttime() {
        return this.accepttime;
    }
    
    public void setAccepttime(Date accepttime) {
        this.accepttime = accepttime;
    }
    public Date getSavetime() {
        return this.savetime;
    }
    
    public void setSavetime(Date savetime) {
        this.savetime = savetime;
    }
    public String getSubmittype() {
        return this.submittype;
    }
    
    public void setSubmittype(String submittype) {
        this.submittype = submittype;
    }
    public String getTransactor() {
        return this.transactor;
    }
    
    public void setTransactor(String transactor) {
        this.transactor = transactor;
    }
    public String getTransactway() {
        return this.transactway;
    }
    
    public void setTransactway(String transactway) {
        this.transactway = transactway;
    }
    public Date getCompletetime() {
        return this.completetime;
    }
    
    public void setCompletetime(Date completetime) {
        this.completetime = completetime;
    }
    public String getStepstate() {
        return this.stepstate;
    }
    
    public void setStepstate(String stepstate) {
        this.stepstate = stepstate;
    }
    public String getSteptype() {
        return this.steptype;
    }
    
    public void setSteptype(String steptype) {
        this.steptype = steptype;
    }
    public BigDecimal getStepnum() {
        return this.stepnum;
    }
    
    public void setStepnum(BigDecimal stepnum) {
        this.stepnum = stepnum;
    }
    public BigDecimal getSteplimit() {
        return this.steplimit;
    }
    
    public void setSteplimit(BigDecimal steplimit) {
        this.steplimit = steplimit;
    }
    public Date getLimittime() {
        return this.limittime;
    }
    
    public void setLimittime(Date limittime) {
        this.limittime = limittime;
    }
    public String getEntrypath() {
        return this.entrypath;
    }
    
    public void setEntrypath(String entrypath) {
        this.entrypath = entrypath;
    }
    public String getEntryparam() {
        return this.entryparam;
    }
    
    public void setEntryparam(String entryparam) {
        this.entryparam = entryparam;
    }
    public String getConsignor() {
        return this.consignor;
    }
    
    public void setConsignor(String consignor) {
        this.consignor = consignor;
    }
    public BigDecimal getLeftdays() {
        return this.leftdays;
    }
    
    public void setLeftdays(BigDecimal leftdays) {
        this.leftdays = leftdays;
    }
    public BigDecimal getOversee() {
        return this.oversee;
    }
    
    public void setOversee(BigDecimal oversee) {
        this.oversee = oversee;
    }
    public String getBiztype() {
        return this.biztype;
    }
    
    public void setBiztype(String biztype) {
        this.biztype = biztype;
    }
    public String getStepalias() {
        return this.stepalias;
    }
    
    public void setStepalias(String stepalias) {
        this.stepalias = stepalias;
    }
    public String getYjzt() {
        return this.yjzt;
    }
    
    public void setYjzt(String yjzt) {
        this.yjzt = yjzt;
    }
    public String getYjxx() {
        return this.yjxx;
    }
    
    public void setYjxx(String yjxx) {
        this.yjxx = yjxx;
    }
    public BigDecimal getReminds() {
        return this.reminds;
    }
    
    public void setReminds(BigDecimal reminds) {
        this.reminds = reminds;
    }
    public String getUnconsent() {
        return this.unconsent;
    }
    
    public void setUnconsent(String unconsent) {
        this.unconsent = unconsent;
    }
    public Date getSharetime() {
        return this.sharetime;
    }
    
    public void setSharetime(Date sharetime) {
        this.sharetime = sharetime;
    }
    public String getSharestate() {
        return this.sharestate;
    }
    
    public void setSharestate(String sharestate) {
        this.sharestate = sharestate;
    }
    public String getGatestate() {
        return this.gatestate;
    }
    
    public void setGatestate(String gatestate) {
        this.gatestate = gatestate;
    }
    public String getSharestateZw() {
        return this.sharestateZw;
    }
    
    public void setSharestateZw(String sharestateZw) {
        this.sharestateZw = sharestateZw;
    }
    public String getSharestateZw1() {
        return this.sharestateZw1;
    }
    
    public void setSharestateZw1(String sharestateZw1) {
        this.sharestateZw1 = sharestateZw1;
    }


	@Override
	public String getIdName() {
		// TODO Auto-generated method stub
		return "wrkid";
	}


	@Override
	public String getDataVersionName() {
		// TODO Auto-generated method stub
		return null;
	}




}


