package com.iawtr.database.dto;
// Generated 2019-1-7 14:12:28 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * WwDjsqTmp generated by hbm2java
 */
public class WwDjsqTmp  implements java.io.Serializable ,DtoInterface {
	private static final long serialVersionUID = 1L;

     private String sqbh;
     private Date sqrq;
     private String djdl;
     private String djxl;
     private BigDecimal sqzsbs;
     private BigDecimal sqfbcz;
     private String qxdm;
     private String spyj;
     private String spr;
     private String spzt;
     private Date sprq;
     private String ajzt;
     private String bz;
     private String sqr;
     private String dccs;
     private String blwd;
     private String dycs;
     private String htbh;
     private String xgzh;
     private String sfzsbd;
     private String sfzsyx;
     private String gyfs;
     private String sqrsfzh;
     private String sqrdhhm;
     private String fsr;
     private String fsyj;
     private Date fsrq;
     private String dklx;
     private String blwdid;
     private String ywmx;

    public WwDjsqTmp() {
    }

	
    public WwDjsqTmp(String sqbh) {
        this.sqbh = sqbh;
    }
    public WwDjsqTmp(String sqbh, Date sqrq, String djdl, String djxl, BigDecimal sqzsbs, BigDecimal sqfbcz, String qxdm, String spyj, String spr, String spzt, Date sprq, String ajzt, String bz, String sqr, String dccs, String blwd, String dycs, String htbh, String xgzh, String sfzsbd, String sfzsyx, String gyfs, String sqrsfzh, String sqrdhhm, String fsr, String fsyj, Date fsrq, String dklx, String blwdid, String ywmx) {
       this.sqbh = sqbh;
       this.sqrq = sqrq;
       this.djdl = djdl;
       this.djxl = djxl;
       this.sqzsbs = sqzsbs;
       this.sqfbcz = sqfbcz;
       this.qxdm = qxdm;
       this.spyj = spyj;
       this.spr = spr;
       this.spzt = spzt;
       this.sprq = sprq;
       this.ajzt = ajzt;
       this.bz = bz;
       this.sqr = sqr;
       this.dccs = dccs;
       this.blwd = blwd;
       this.dycs = dycs;
       this.htbh = htbh;
       this.xgzh = xgzh;
       this.sfzsbd = sfzsbd;
       this.sfzsyx = sfzsyx;
       this.gyfs = gyfs;
       this.sqrsfzh = sqrsfzh;
       this.sqrdhhm = sqrdhhm;
       this.fsr = fsr;
       this.fsyj = fsyj;
       this.fsrq = fsrq;
       this.dklx = dklx;
       this.blwdid = blwdid;
       this.ywmx = ywmx;
    }
   
    public String getSqbh() {
        return this.sqbh;
    }
    
    public void setSqbh(String sqbh) {
        this.sqbh = sqbh;
    }
    public Date getSqrq() {
        return this.sqrq;
    }
    
    public void setSqrq(Date sqrq) {
        this.sqrq = sqrq;
    }
    public String getDjdl() {
        return this.djdl;
    }
    
    public void setDjdl(String djdl) {
        this.djdl = djdl;
    }
    public String getDjxl() {
        return this.djxl;
    }
    
    public void setDjxl(String djxl) {
        this.djxl = djxl;
    }
    public BigDecimal getSqzsbs() {
        return this.sqzsbs;
    }
    
    public void setSqzsbs(BigDecimal sqzsbs) {
        this.sqzsbs = sqzsbs;
    }
    public BigDecimal getSqfbcz() {
        return this.sqfbcz;
    }
    
    public void setSqfbcz(BigDecimal sqfbcz) {
        this.sqfbcz = sqfbcz;
    }
    public String getQxdm() {
        return this.qxdm;
    }
    
    public void setQxdm(String qxdm) {
        this.qxdm = qxdm;
    }
    public String getSpyj() {
        return this.spyj;
    }
    
    public void setSpyj(String spyj) {
        this.spyj = spyj;
    }
    public String getSpr() {
        return this.spr;
    }
    
    public void setSpr(String spr) {
        this.spr = spr;
    }
    public String getSpzt() {
        return this.spzt;
    }
    
    public void setSpzt(String spzt) {
        this.spzt = spzt;
    }
    public Date getSprq() {
        return this.sprq;
    }
    
    public void setSprq(Date sprq) {
        this.sprq = sprq;
    }
    public String getAjzt() {
        return this.ajzt;
    }
    
    public void setAjzt(String ajzt) {
        this.ajzt = ajzt;
    }
    public String getBz() {
        return this.bz;
    }
    
    public void setBz(String bz) {
        this.bz = bz;
    }
    public String getSqr() {
        return this.sqr;
    }
    
    public void setSqr(String sqr) {
        this.sqr = sqr;
    }
    public String getDccs() {
        return this.dccs;
    }
    
    public void setDccs(String dccs) {
        this.dccs = dccs;
    }
    public String getBlwd() {
        return this.blwd;
    }
    
    public void setBlwd(String blwd) {
        this.blwd = blwd;
    }
    public String getDycs() {
        return this.dycs;
    }
    
    public void setDycs(String dycs) {
        this.dycs = dycs;
    }
    public String getHtbh() {
        return this.htbh;
    }
    
    public void setHtbh(String htbh) {
        this.htbh = htbh;
    }
    public String getXgzh() {
        return this.xgzh;
    }
    
    public void setXgzh(String xgzh) {
        this.xgzh = xgzh;
    }
    public String getSfzsbd() {
        return this.sfzsbd;
    }
    
    public void setSfzsbd(String sfzsbd) {
        this.sfzsbd = sfzsbd;
    }
    public String getSfzsyx() {
        return this.sfzsyx;
    }
    
    public void setSfzsyx(String sfzsyx) {
        this.sfzsyx = sfzsyx;
    }
    public String getGyfs() {
        return this.gyfs;
    }
    
    public void setGyfs(String gyfs) {
        this.gyfs = gyfs;
    }
    public String getSqrsfzh() {
        return this.sqrsfzh;
    }
    
    public void setSqrsfzh(String sqrsfzh) {
        this.sqrsfzh = sqrsfzh;
    }
    public String getSqrdhhm() {
        return this.sqrdhhm;
    }
    
    public void setSqrdhhm(String sqrdhhm) {
        this.sqrdhhm = sqrdhhm;
    }
    public String getFsr() {
        return this.fsr;
    }
    
    public void setFsr(String fsr) {
        this.fsr = fsr;
    }
    public String getFsyj() {
        return this.fsyj;
    }
    
    public void setFsyj(String fsyj) {
        this.fsyj = fsyj;
    }
    public Date getFsrq() {
        return this.fsrq;
    }
    
    public void setFsrq(Date fsrq) {
        this.fsrq = fsrq;
    }
    public String getDklx() {
        return this.dklx;
    }
    
    public void setDklx(String dklx) {
        this.dklx = dklx;
    }
    public String getBlwdid() {
        return this.blwdid;
    }
    
    public void setBlwdid(String blwdid) {
        this.blwdid = blwdid;
    }
    public String getYwmx() {
        return this.ywmx;
    }
    
    public void setYwmx(String ywmx) {
        this.ywmx = ywmx;
    }


	@Override
	public String getIdName() {
		// TODO Auto-generated method stub
		return "sqbh";
	}


	@Override
	public String getDataVersionName() {
		// TODO Auto-generated method stub
		return null;
	}




}


