package com.iawtr.database.dto;
// Generated 2019-1-7 14:12:28 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * WwDysqTmp generated by hbm2java
 */
public class WwDysqTmp  implements java.io.Serializable ,DtoInterface {
	private static final long serialVersionUID = 1L;

     private String sqbh;
     private String xgzh;
     private String dylx;
     private BigDecimal dysw;
     private String zwr;
     private String zwrzjlx;
     private String zwrzjh;
     private String dyfs;
     private BigDecimal dymj;
     private String zjjzwzl;
     private String zjjzwdyfw;
     private BigDecimal bdbzzqse;
     private BigDecimal pgje;
     private String dbfw;
     private String zgzqqdss;
     private BigDecimal zgzqse;
     private String dyqx;
     private Date qlqssj;
     private Date qljssj;
     private String bdcdyh;

    public WwDysqTmp() {
    }

	
    public WwDysqTmp(String sqbh) {
        this.sqbh = sqbh;
    }
    public WwDysqTmp(String sqbh, String xgzh, String dylx, BigDecimal dysw, String zwr, String zwrzjlx, String zwrzjh, String dyfs, BigDecimal dymj, String zjjzwzl, String zjjzwdyfw, BigDecimal bdbzzqse, BigDecimal pgje, String dbfw, String zgzqqdss, BigDecimal zgzqse, String dyqx, Date qlqssj, Date qljssj, String bdcdyh) {
       this.sqbh = sqbh;
       this.xgzh = xgzh;
       this.dylx = dylx;
       this.dysw = dysw;
       this.zwr = zwr;
       this.zwrzjlx = zwrzjlx;
       this.zwrzjh = zwrzjh;
       this.dyfs = dyfs;
       this.dymj = dymj;
       this.zjjzwzl = zjjzwzl;
       this.zjjzwdyfw = zjjzwdyfw;
       this.bdbzzqse = bdbzzqse;
       this.pgje = pgje;
       this.dbfw = dbfw;
       this.zgzqqdss = zgzqqdss;
       this.zgzqse = zgzqse;
       this.dyqx = dyqx;
       this.qlqssj = qlqssj;
       this.qljssj = qljssj;
       this.bdcdyh = bdcdyh;
    }
   
    public String getSqbh() {
        return this.sqbh;
    }
    
    public void setSqbh(String sqbh) {
        this.sqbh = sqbh;
    }
    public String getXgzh() {
        return this.xgzh;
    }
    
    public void setXgzh(String xgzh) {
        this.xgzh = xgzh;
    }
    public String getDylx() {
        return this.dylx;
    }
    
    public void setDylx(String dylx) {
        this.dylx = dylx;
    }
    public BigDecimal getDysw() {
        return this.dysw;
    }
    
    public void setDysw(BigDecimal dysw) {
        this.dysw = dysw;
    }
    public String getZwr() {
        return this.zwr;
    }
    
    public void setZwr(String zwr) {
        this.zwr = zwr;
    }
    public String getZwrzjlx() {
        return this.zwrzjlx;
    }
    
    public void setZwrzjlx(String zwrzjlx) {
        this.zwrzjlx = zwrzjlx;
    }
    public String getZwrzjh() {
        return this.zwrzjh;
    }
    
    public void setZwrzjh(String zwrzjh) {
        this.zwrzjh = zwrzjh;
    }
    public String getDyfs() {
        return this.dyfs;
    }
    
    public void setDyfs(String dyfs) {
        this.dyfs = dyfs;
    }
    public BigDecimal getDymj() {
        return this.dymj;
    }
    
    public void setDymj(BigDecimal dymj) {
        this.dymj = dymj;
    }
    public String getZjjzwzl() {
        return this.zjjzwzl;
    }
    
    public void setZjjzwzl(String zjjzwzl) {
        this.zjjzwzl = zjjzwzl;
    }
    public String getZjjzwdyfw() {
        return this.zjjzwdyfw;
    }
    
    public void setZjjzwdyfw(String zjjzwdyfw) {
        this.zjjzwdyfw = zjjzwdyfw;
    }
    public BigDecimal getBdbzzqse() {
        return this.bdbzzqse;
    }
    
    public void setBdbzzqse(BigDecimal bdbzzqse) {
        this.bdbzzqse = bdbzzqse;
    }
    public BigDecimal getPgje() {
        return this.pgje;
    }
    
    public void setPgje(BigDecimal pgje) {
        this.pgje = pgje;
    }
    public String getDbfw() {
        return this.dbfw;
    }
    
    public void setDbfw(String dbfw) {
        this.dbfw = dbfw;
    }
    public String getZgzqqdss() {
        return this.zgzqqdss;
    }
    
    public void setZgzqqdss(String zgzqqdss) {
        this.zgzqqdss = zgzqqdss;
    }
    public BigDecimal getZgzqse() {
        return this.zgzqse;
    }
    
    public void setZgzqse(BigDecimal zgzqse) {
        this.zgzqse = zgzqse;
    }
    public String getDyqx() {
        return this.dyqx;
    }
    
    public void setDyqx(String dyqx) {
        this.dyqx = dyqx;
    }
    public Date getQlqssj() {
        return this.qlqssj;
    }
    
    public void setQlqssj(Date qlqssj) {
        this.qlqssj = qlqssj;
    }
    public Date getQljssj() {
        return this.qljssj;
    }
    
    public void setQljssj(Date qljssj) {
        this.qljssj = qljssj;
    }
    public String getBdcdyh() {
        return this.bdcdyh;
    }
    
    public void setBdcdyh(String bdcdyh) {
        this.bdcdyh = bdcdyh;
    }


	@Override
	public String getIdName() {
		// TODO Auto-generated method stub
		return "sqbh";
	}


	@Override
	public String getDataVersionName() {
		// TODO Auto-generated method stub
		return null;
	}




}


