package com.iawtr.database.dto;
// Generated 2019-1-7 14:12:28 by Hibernate Tools 3.2.1.GA


import java.sql.Blob;
import java.util.Date;

/**
 * WwFjqdTmp generated by hbm2java
 */
public class WwFjqdTmp  implements java.io.Serializable ,DtoInterface {
	private static final long serialVersionUID = 1L;

     private String qdid;
     private String sqbh;
     private String xh;
     private String fjmc;
     private String fjlx;
     private String ftplj;
     private String fjdx;
     private Blob fjnr;
     private String fjzt;
     private Date fjtjsj;
     private String fjkzm;
     private String fjml;
     private String fjzdpzml;

    public WwFjqdTmp() {
    }

	
    public WwFjqdTmp(String qdid) {
        this.qdid = qdid;
    }
    public WwFjqdTmp(String qdid, String sqbh, String xh, String fjmc, String fjlx, String ftplj, String fjdx, Blob fjnr, String fjzt, Date fjtjsj, String fjkzm, String fjml, String fjzdpzml) {
       this.qdid = qdid;
       this.sqbh = sqbh;
       this.xh = xh;
       this.fjmc = fjmc;
       this.fjlx = fjlx;
       this.ftplj = ftplj;
       this.fjdx = fjdx;
       this.fjnr = fjnr;
       this.fjzt = fjzt;
       this.fjtjsj = fjtjsj;
       this.fjkzm = fjkzm;
       this.fjml = fjml;
       this.fjzdpzml = fjzdpzml;
    }
   
    public String getQdid() {
        return this.qdid;
    }
    
    public void setQdid(String qdid) {
        this.qdid = qdid;
    }
    public String getSqbh() {
        return this.sqbh;
    }
    
    public void setSqbh(String sqbh) {
        this.sqbh = sqbh;
    }
    public String getXh() {
        return this.xh;
    }
    
    public void setXh(String xh) {
        this.xh = xh;
    }
    public String getFjmc() {
        return this.fjmc;
    }
    
    public void setFjmc(String fjmc) {
        this.fjmc = fjmc;
    }
    public String getFjlx() {
        return this.fjlx;
    }
    
    public void setFjlx(String fjlx) {
        this.fjlx = fjlx;
    }
    public String getFtplj() {
        return this.ftplj;
    }
    
    public void setFtplj(String ftplj) {
        this.ftplj = ftplj;
    }
    public String getFjdx() {
        return this.fjdx;
    }
    
    public void setFjdx(String fjdx) {
        this.fjdx = fjdx;
    }
    public Blob getFjnr() {
        return this.fjnr;
    }
    
    public void setFjnr(Blob fjnr) {
        this.fjnr = fjnr;
    }
    public String getFjzt() {
        return this.fjzt;
    }
    
    public void setFjzt(String fjzt) {
        this.fjzt = fjzt;
    }
    public Date getFjtjsj() {
        return this.fjtjsj;
    }
    
    public void setFjtjsj(Date fjtjsj) {
        this.fjtjsj = fjtjsj;
    }
    public String getFjkzm() {
        return this.fjkzm;
    }
    
    public void setFjkzm(String fjkzm) {
        this.fjkzm = fjkzm;
    }
    public String getFjml() {
        return this.fjml;
    }
    
    public void setFjml(String fjml) {
        this.fjml = fjml;
    }
    public String getFjzdpzml() {
        return this.fjzdpzml;
    }
    
    public void setFjzdpzml(String fjzdpzml) {
        this.fjzdpzml = fjzdpzml;
    }


	@Override
	public String getIdName() {
		// TODO Auto-generated method stub
		return "qdid";
	}


	@Override
	public String getDataVersionName() {
		// TODO Auto-generated method stub
		return null;
	}




}


