package com.iawtr.database.dto;
// Generated 2019-1-7 13:08:49 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * WwTsglTmp generated by hbm2java
 */
public class WwTsglTmp  implements java.io.Serializable ,DtoInterface {
	private static final long serialVersionUID = 1L;

     private String glbm;
     private String sqbh;
     private String bdclx;
     private String tstybm;
     private String bdcdyh;
     private String djzl;
     private String glms;
     private Date cssj;

    public WwTsglTmp() {
    }

	
    public WwTsglTmp(String glbm) {
        this.glbm = glbm;
    }
    public WwTsglTmp(String glbm, String sqbh, String bdclx, String tstybm, String bdcdyh, String djzl, String glms, Date cssj) {
       this.glbm = glbm;
       this.sqbh = sqbh;
       this.bdclx = bdclx;
       this.tstybm = tstybm;
       this.bdcdyh = bdcdyh;
       this.djzl = djzl;
       this.glms = glms;
       this.cssj = cssj;
    }
   
    public String getGlbm() {
        return this.glbm;
    }
    
    public void setGlbm(String glbm) {
        this.glbm = glbm;
    }
    public String getSqbh() {
        return this.sqbh;
    }
    
    public void setSqbh(String sqbh) {
        this.sqbh = sqbh;
    }
    public String getBdclx() {
        return this.bdclx;
    }
    
    public void setBdclx(String bdclx) {
        this.bdclx = bdclx;
    }
    public String getTstybm() {
        return this.tstybm;
    }
    
    public void setTstybm(String tstybm) {
        this.tstybm = tstybm;
    }
    public String getBdcdyh() {
        return this.bdcdyh;
    }
    
    public void setBdcdyh(String bdcdyh) {
        this.bdcdyh = bdcdyh;
    }
    public String getDjzl() {
        return this.djzl;
    }
    
    public void setDjzl(String djzl) {
        this.djzl = djzl;
    }
    public String getGlms() {
        return this.glms;
    }
    
    public void setGlms(String glms) {
        this.glms = glms;
    }
    public Date getCssj() {
        return this.cssj;
    }
    
    public void setCssj(Date cssj) {
        this.cssj = cssj;
    }


	@Override
	public String getIdName() {
		// TODO Auto-generated method stub
		return "glbm";
	}


	@Override
	public String getDataVersionName() {
		// TODO Auto-generated method stub
		return null;
	}




}


