package com.iawtr.database.dto;
// Generated 2019-1-7 14:12:28 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;

/**
 * ZdQsdc generated by hbm2java
 */
public class ZdQsdc  implements java.io.Serializable ,DtoInterface {
	private static final long serialVersionUID = 1L;

     private String tstybm;
     private String zdlx;
     private String zdtybm;
     private String sjzdtybm;
     private String bdcdyh;
     private String djh;
     private String qsdwdm;
     private String qsdwmc;
     private String zldwdm;
     private String zldwmc;
     private String tdzl;
     private String qlrmc;
     private String qllx;
     private String qlxz;
     private String tdsyz;
     private BigDecimal dymj;
     private BigDecimal ftmj;
     private String sfgyz;
     private String pztdyt;
     private String sjtdyt;
     private String gysyqqk;
     private BigDecimal scmj;
     private BigDecimal fzmj;
     private String sztfh;
     private BigDecimal jzmj;
     private BigDecimal jzwzdmj;
     private BigDecimal jzrjl;
     private BigDecimal jzmd;
     private String jzxg;
     private String qdfs;
     private String szd;
     private String szn;
     private String szx;
     private String szb;
     private String sm;
     private String zdzt;
     private String zbclxxx;
     private String zdtzm;
     private String qlsdfs;
     private String jzdcy;
     private String zjwts;
     private String zdcthzy;
     private Date zdcthzrq;
     private String qsdcjs;
     private String dcy;
     private Date dcrq;
     private String jzbs;
     private String djkzjs;
     private String kzy;
     private Date kzrq;
     private String dcshyj;
     private String dcshr;
     private Date dcshrq;
     private BigDecimal tdzmj;
     private BigDecimal nydmj;
     private BigDecimal gdmj;
     private BigDecimal ydmj;
     private BigDecimal ldmj;
     private BigDecimal mcdmj;
     private BigDecimal nydqtmj;
     private BigDecimal jsydmj;
     private BigDecimal jmdmj;
     private BigDecimal jtydmj;
     private BigDecimal symj;
     private BigDecimal jsydqtmj;
     private BigDecimal wlydmj;
     private String gmjjhyfldm;
     private String ybzddm;
     private String blc;
     private String jzdwsm;
     private String zyqsjzzxsm;
     private String jzwlx;
     private String jzwqs;
     private String syqx;
     private Date qsrq;
     private Date zzrq;
     private String zddj;
     private BigDecimal zdjg;
     private BigDecimal sbdj;
     private String dlrxm;
     private String dlrzjlx;
     private String dlrzjh;
     private String dlrdh;
     private String pzwh;
     private String dcbbh;
     private Blob zdt;
     private Blob zdct;
     private BigDecimal lifecycle;
     private String jzlb;
     private String appid;
     private String ytstybm;
     private String qlxz1;
     private String tdzl1;
     private String yzdtybm;
     private BigDecimal fzmj1;
     private String tdzl2;
     private String dcrgzdmzh;
     private String kzygzdmzh;
     private String dcshrgzdmzh;
     private String sharestate;
     private String bgjzxx;
     private String bgtsxx;
     private String rghsry;
     private Date rghsrq;
     private String isrghs;
     private String dcdw;
     private Date dcshrq2;
     private String dcshr2;
     private String dcshyj2;
     private String tdqslyzmcl;
     private BigDecimal qtyzgytdsyqmj;
     private String kjzb;
     private String wzsm;
     private BigDecimal txmj;
     private Date sharetime;
     private String ghrjl;

    public ZdQsdc() {
    }

	
    public ZdQsdc(String tstybm) {
        this.tstybm = tstybm;
    }
    public ZdQsdc(String tstybm, String zdlx, String zdtybm, String sjzdtybm, String bdcdyh, String djh, String qsdwdm, String qsdwmc, String zldwdm, String zldwmc, String tdzl, String qlrmc, String qllx, String qlxz, String tdsyz, BigDecimal dymj, BigDecimal ftmj, String sfgyz, String pztdyt, String sjtdyt, String gysyqqk, BigDecimal scmj, BigDecimal fzmj, String sztfh, BigDecimal jzmj, BigDecimal jzwzdmj, BigDecimal jzrjl, BigDecimal jzmd, String jzxg, String qdfs, String szd, String szn, String szx, String szb, String sm, String zdzt, String zbclxxx, String zdtzm, String qlsdfs, String jzdcy, String zjwts, String zdcthzy, Date zdcthzrq, String qsdcjs, String dcy, Date dcrq, String jzbs, String djkzjs, String kzy, Date kzrq, String dcshyj, String dcshr, Date dcshrq, BigDecimal tdzmj, BigDecimal nydmj, BigDecimal gdmj, BigDecimal ydmj, BigDecimal ldmj, BigDecimal mcdmj, BigDecimal nydqtmj, BigDecimal jsydmj, BigDecimal jmdmj, BigDecimal jtydmj, BigDecimal symj, BigDecimal jsydqtmj, BigDecimal wlydmj, String gmjjhyfldm, String ybzddm, String blc, String jzdwsm, String zyqsjzzxsm, String jzwlx, String jzwqs, String syqx, Date qsrq, Date zzrq, String zddj, BigDecimal zdjg, BigDecimal sbdj, String dlrxm, String dlrzjlx, String dlrzjh, String dlrdh, String pzwh, String dcbbh, Blob zdt, Blob zdct, BigDecimal lifecycle, String jzlb, String appid, String ytstybm, String qlxz1, String tdzl1, String yzdtybm, BigDecimal fzmj1, String tdzl2, String dcrgzdmzh, String kzygzdmzh, String dcshrgzdmzh, String sharestate, String bgjzxx, String bgtsxx, String rghsry, Date rghsrq, String isrghs, String dcdw, Date dcshrq2, String dcshr2, String dcshyj2, String tdqslyzmcl, BigDecimal qtyzgytdsyqmj, String kjzb, String wzsm, BigDecimal txmj, Date sharetime, String ghrjl) {
       this.tstybm = tstybm;
       this.zdlx = zdlx;
       this.zdtybm = zdtybm;
       this.sjzdtybm = sjzdtybm;
       this.bdcdyh = bdcdyh;
       this.djh = djh;
       this.qsdwdm = qsdwdm;
       this.qsdwmc = qsdwmc;
       this.zldwdm = zldwdm;
       this.zldwmc = zldwmc;
       this.tdzl = tdzl;
       this.qlrmc = qlrmc;
       this.qllx = qllx;
       this.qlxz = qlxz;
       this.tdsyz = tdsyz;
       this.dymj = dymj;
       this.ftmj = ftmj;
       this.sfgyz = sfgyz;
       this.pztdyt = pztdyt;
       this.sjtdyt = sjtdyt;
       this.gysyqqk = gysyqqk;
       this.scmj = scmj;
       this.fzmj = fzmj;
       this.sztfh = sztfh;
       this.jzmj = jzmj;
       this.jzwzdmj = jzwzdmj;
       this.jzrjl = jzrjl;
       this.jzmd = jzmd;
       this.jzxg = jzxg;
       this.qdfs = qdfs;
       this.szd = szd;
       this.szn = szn;
       this.szx = szx;
       this.szb = szb;
       this.sm = sm;
       this.zdzt = zdzt;
       this.zbclxxx = zbclxxx;
       this.zdtzm = zdtzm;
       this.qlsdfs = qlsdfs;
       this.jzdcy = jzdcy;
       this.zjwts = zjwts;
       this.zdcthzy = zdcthzy;
       this.zdcthzrq = zdcthzrq;
       this.qsdcjs = qsdcjs;
       this.dcy = dcy;
       this.dcrq = dcrq;
       this.jzbs = jzbs;
       this.djkzjs = djkzjs;
       this.kzy = kzy;
       this.kzrq = kzrq;
       this.dcshyj = dcshyj;
       this.dcshr = dcshr;
       this.dcshrq = dcshrq;
       this.tdzmj = tdzmj;
       this.nydmj = nydmj;
       this.gdmj = gdmj;
       this.ydmj = ydmj;
       this.ldmj = ldmj;
       this.mcdmj = mcdmj;
       this.nydqtmj = nydqtmj;
       this.jsydmj = jsydmj;
       this.jmdmj = jmdmj;
       this.jtydmj = jtydmj;
       this.symj = symj;
       this.jsydqtmj = jsydqtmj;
       this.wlydmj = wlydmj;
       this.gmjjhyfldm = gmjjhyfldm;
       this.ybzddm = ybzddm;
       this.blc = blc;
       this.jzdwsm = jzdwsm;
       this.zyqsjzzxsm = zyqsjzzxsm;
       this.jzwlx = jzwlx;
       this.jzwqs = jzwqs;
       this.syqx = syqx;
       this.qsrq = qsrq;
       this.zzrq = zzrq;
       this.zddj = zddj;
       this.zdjg = zdjg;
       this.sbdj = sbdj;
       this.dlrxm = dlrxm;
       this.dlrzjlx = dlrzjlx;
       this.dlrzjh = dlrzjh;
       this.dlrdh = dlrdh;
       this.pzwh = pzwh;
       this.dcbbh = dcbbh;
       this.zdt = zdt;
       this.zdct = zdct;
       this.lifecycle = lifecycle;
       this.jzlb = jzlb;
       this.appid = appid;
       this.ytstybm = ytstybm;
       this.qlxz1 = qlxz1;
       this.tdzl1 = tdzl1;
       this.yzdtybm = yzdtybm;
       this.fzmj1 = fzmj1;
       this.tdzl2 = tdzl2;
       this.dcrgzdmzh = dcrgzdmzh;
       this.kzygzdmzh = kzygzdmzh;
       this.dcshrgzdmzh = dcshrgzdmzh;
       this.sharestate = sharestate;
       this.bgjzxx = bgjzxx;
       this.bgtsxx = bgtsxx;
       this.rghsry = rghsry;
       this.rghsrq = rghsrq;
       this.isrghs = isrghs;
       this.dcdw = dcdw;
       this.dcshrq2 = dcshrq2;
       this.dcshr2 = dcshr2;
       this.dcshyj2 = dcshyj2;
       this.tdqslyzmcl = tdqslyzmcl;
       this.qtyzgytdsyqmj = qtyzgytdsyqmj;
       this.kjzb = kjzb;
       this.wzsm = wzsm;
       this.txmj = txmj;
       this.sharetime = sharetime;
       this.ghrjl = ghrjl;
    }
   
    public String getTstybm() {
        return this.tstybm;
    }
    
    public void setTstybm(String tstybm) {
        this.tstybm = tstybm;
    }
    public String getZdlx() {
        return this.zdlx;
    }
    
    public void setZdlx(String zdlx) {
        this.zdlx = zdlx;
    }
    public String getZdtybm() {
        return this.zdtybm;
    }
    
    public void setZdtybm(String zdtybm) {
        this.zdtybm = zdtybm;
    }
    public String getSjzdtybm() {
        return this.sjzdtybm;
    }
    
    public void setSjzdtybm(String sjzdtybm) {
        this.sjzdtybm = sjzdtybm;
    }
    public String getBdcdyh() {
        return this.bdcdyh;
    }
    
    public void setBdcdyh(String bdcdyh) {
        this.bdcdyh = bdcdyh;
    }
    public String getDjh() {
        return this.djh;
    }
    
    public void setDjh(String djh) {
        this.djh = djh;
    }
    public String getQsdwdm() {
        return this.qsdwdm;
    }
    
    public void setQsdwdm(String qsdwdm) {
        this.qsdwdm = qsdwdm;
    }
    public String getQsdwmc() {
        return this.qsdwmc;
    }
    
    public void setQsdwmc(String qsdwmc) {
        this.qsdwmc = qsdwmc;
    }
    public String getZldwdm() {
        return this.zldwdm;
    }
    
    public void setZldwdm(String zldwdm) {
        this.zldwdm = zldwdm;
    }
    public String getZldwmc() {
        return this.zldwmc;
    }
    
    public void setZldwmc(String zldwmc) {
        this.zldwmc = zldwmc;
    }
    public String getTdzl() {
        return this.tdzl;
    }
    
    public void setTdzl(String tdzl) {
        this.tdzl = tdzl;
    }
    public String getQlrmc() {
        return this.qlrmc;
    }
    
    public void setQlrmc(String qlrmc) {
        this.qlrmc = qlrmc;
    }
    public String getQllx() {
        return this.qllx;
    }
    
    public void setQllx(String qllx) {
        this.qllx = qllx;
    }
    public String getQlxz() {
        return this.qlxz;
    }
    
    public void setQlxz(String qlxz) {
        this.qlxz = qlxz;
    }
    public String getTdsyz() {
        return this.tdsyz;
    }
    
    public void setTdsyz(String tdsyz) {
        this.tdsyz = tdsyz;
    }
    public BigDecimal getDymj() {
        return this.dymj;
    }
    
    public void setDymj(BigDecimal dymj) {
        this.dymj = dymj;
    }
    public BigDecimal getFtmj() {
        return this.ftmj;
    }
    
    public void setFtmj(BigDecimal ftmj) {
        this.ftmj = ftmj;
    }
    public String getSfgyz() {
        return this.sfgyz;
    }
    
    public void setSfgyz(String sfgyz) {
        this.sfgyz = sfgyz;
    }
    public String getPztdyt() {
        return this.pztdyt;
    }
    
    public void setPztdyt(String pztdyt) {
        this.pztdyt = pztdyt;
    }
    public String getSjtdyt() {
        return this.sjtdyt;
    }
    
    public void setSjtdyt(String sjtdyt) {
        this.sjtdyt = sjtdyt;
    }
    public String getGysyqqk() {
        return this.gysyqqk;
    }
    
    public void setGysyqqk(String gysyqqk) {
        this.gysyqqk = gysyqqk;
    }
    public BigDecimal getScmj() {
        return this.scmj;
    }
    
    public void setScmj(BigDecimal scmj) {
        this.scmj = scmj;
    }
    public BigDecimal getFzmj() {
        return this.fzmj;
    }
    
    public void setFzmj(BigDecimal fzmj) {
        this.fzmj = fzmj;
    }
    public String getSztfh() {
        return this.sztfh;
    }
    
    public void setSztfh(String sztfh) {
        this.sztfh = sztfh;
    }
    public BigDecimal getJzmj() {
        return this.jzmj;
    }
    
    public void setJzmj(BigDecimal jzmj) {
        this.jzmj = jzmj;
    }
    public BigDecimal getJzwzdmj() {
        return this.jzwzdmj;
    }
    
    public void setJzwzdmj(BigDecimal jzwzdmj) {
        this.jzwzdmj = jzwzdmj;
    }
    public BigDecimal getJzrjl() {
        return this.jzrjl;
    }
    
    public void setJzrjl(BigDecimal jzrjl) {
        this.jzrjl = jzrjl;
    }
    public BigDecimal getJzmd() {
        return this.jzmd;
    }
    
    public void setJzmd(BigDecimal jzmd) {
        this.jzmd = jzmd;
    }
    public String getJzxg() {
        return this.jzxg;
    }
    
    public void setJzxg(String jzxg) {
        this.jzxg = jzxg;
    }
    public String getQdfs() {
        return this.qdfs;
    }
    
    public void setQdfs(String qdfs) {
        this.qdfs = qdfs;
    }
    public String getSzd() {
        return this.szd;
    }
    
    public void setSzd(String szd) {
        this.szd = szd;
    }
    public String getSzn() {
        return this.szn;
    }
    
    public void setSzn(String szn) {
        this.szn = szn;
    }
    public String getSzx() {
        return this.szx;
    }
    
    public void setSzx(String szx) {
        this.szx = szx;
    }
    public String getSzb() {
        return this.szb;
    }
    
    public void setSzb(String szb) {
        this.szb = szb;
    }
    public String getSm() {
        return this.sm;
    }
    
    public void setSm(String sm) {
        this.sm = sm;
    }
    public String getZdzt() {
        return this.zdzt;
    }
    
    public void setZdzt(String zdzt) {
        this.zdzt = zdzt;
    }
    public String getZbclxxx() {
        return this.zbclxxx;
    }
    
    public void setZbclxxx(String zbclxxx) {
        this.zbclxxx = zbclxxx;
    }
    public String getZdtzm() {
        return this.zdtzm;
    }
    
    public void setZdtzm(String zdtzm) {
        this.zdtzm = zdtzm;
    }
    public String getQlsdfs() {
        return this.qlsdfs;
    }
    
    public void setQlsdfs(String qlsdfs) {
        this.qlsdfs = qlsdfs;
    }
    public String getJzdcy() {
        return this.jzdcy;
    }
    
    public void setJzdcy(String jzdcy) {
        this.jzdcy = jzdcy;
    }
    public String getZjwts() {
        return this.zjwts;
    }
    
    public void setZjwts(String zjwts) {
        this.zjwts = zjwts;
    }
    public String getZdcthzy() {
        return this.zdcthzy;
    }
    
    public void setZdcthzy(String zdcthzy) {
        this.zdcthzy = zdcthzy;
    }
    public Date getZdcthzrq() {
        return this.zdcthzrq;
    }
    
    public void setZdcthzrq(Date zdcthzrq) {
        this.zdcthzrq = zdcthzrq;
    }
    public String getQsdcjs() {
        return this.qsdcjs;
    }
    
    public void setQsdcjs(String qsdcjs) {
        this.qsdcjs = qsdcjs;
    }
    public String getDcy() {
        return this.dcy;
    }
    
    public void setDcy(String dcy) {
        this.dcy = dcy;
    }
    public Date getDcrq() {
        return this.dcrq;
    }
    
    public void setDcrq(Date dcrq) {
        this.dcrq = dcrq;
    }
    public String getJzbs() {
        return this.jzbs;
    }
    
    public void setJzbs(String jzbs) {
        this.jzbs = jzbs;
    }
    public String getDjkzjs() {
        return this.djkzjs;
    }
    
    public void setDjkzjs(String djkzjs) {
        this.djkzjs = djkzjs;
    }
    public String getKzy() {
        return this.kzy;
    }
    
    public void setKzy(String kzy) {
        this.kzy = kzy;
    }
    public Date getKzrq() {
        return this.kzrq;
    }
    
    public void setKzrq(Date kzrq) {
        this.kzrq = kzrq;
    }
    public String getDcshyj() {
        return this.dcshyj;
    }
    
    public void setDcshyj(String dcshyj) {
        this.dcshyj = dcshyj;
    }
    public String getDcshr() {
        return this.dcshr;
    }
    
    public void setDcshr(String dcshr) {
        this.dcshr = dcshr;
    }
    public Date getDcshrq() {
        return this.dcshrq;
    }
    
    public void setDcshrq(Date dcshrq) {
        this.dcshrq = dcshrq;
    }
    public BigDecimal getTdzmj() {
        return this.tdzmj;
    }
    
    public void setTdzmj(BigDecimal tdzmj) {
        this.tdzmj = tdzmj;
    }
    public BigDecimal getNydmj() {
        return this.nydmj;
    }
    
    public void setNydmj(BigDecimal nydmj) {
        this.nydmj = nydmj;
    }
    public BigDecimal getGdmj() {
        return this.gdmj;
    }
    
    public void setGdmj(BigDecimal gdmj) {
        this.gdmj = gdmj;
    }
    public BigDecimal getYdmj() {
        return this.ydmj;
    }
    
    public void setYdmj(BigDecimal ydmj) {
        this.ydmj = ydmj;
    }
    public BigDecimal getLdmj() {
        return this.ldmj;
    }
    
    public void setLdmj(BigDecimal ldmj) {
        this.ldmj = ldmj;
    }
    public BigDecimal getMcdmj() {
        return this.mcdmj;
    }
    
    public void setMcdmj(BigDecimal mcdmj) {
        this.mcdmj = mcdmj;
    }
    public BigDecimal getNydqtmj() {
        return this.nydqtmj;
    }
    
    public void setNydqtmj(BigDecimal nydqtmj) {
        this.nydqtmj = nydqtmj;
    }
    public BigDecimal getJsydmj() {
        return this.jsydmj;
    }
    
    public void setJsydmj(BigDecimal jsydmj) {
        this.jsydmj = jsydmj;
    }
    public BigDecimal getJmdmj() {
        return this.jmdmj;
    }
    
    public void setJmdmj(BigDecimal jmdmj) {
        this.jmdmj = jmdmj;
    }
    public BigDecimal getJtydmj() {
        return this.jtydmj;
    }
    
    public void setJtydmj(BigDecimal jtydmj) {
        this.jtydmj = jtydmj;
    }
    public BigDecimal getSymj() {
        return this.symj;
    }
    
    public void setSymj(BigDecimal symj) {
        this.symj = symj;
    }
    public BigDecimal getJsydqtmj() {
        return this.jsydqtmj;
    }
    
    public void setJsydqtmj(BigDecimal jsydqtmj) {
        this.jsydqtmj = jsydqtmj;
    }
    public BigDecimal getWlydmj() {
        return this.wlydmj;
    }
    
    public void setWlydmj(BigDecimal wlydmj) {
        this.wlydmj = wlydmj;
    }
    public String getGmjjhyfldm() {
        return this.gmjjhyfldm;
    }
    
    public void setGmjjhyfldm(String gmjjhyfldm) {
        this.gmjjhyfldm = gmjjhyfldm;
    }
    public String getYbzddm() {
        return this.ybzddm;
    }
    
    public void setYbzddm(String ybzddm) {
        this.ybzddm = ybzddm;
    }
    public String getBlc() {
        return this.blc;
    }
    
    public void setBlc(String blc) {
        this.blc = blc;
    }
    public String getJzdwsm() {
        return this.jzdwsm;
    }
    
    public void setJzdwsm(String jzdwsm) {
        this.jzdwsm = jzdwsm;
    }
    public String getZyqsjzzxsm() {
        return this.zyqsjzzxsm;
    }
    
    public void setZyqsjzzxsm(String zyqsjzzxsm) {
        this.zyqsjzzxsm = zyqsjzzxsm;
    }
    public String getJzwlx() {
        return this.jzwlx;
    }
    
    public void setJzwlx(String jzwlx) {
        this.jzwlx = jzwlx;
    }
    public String getJzwqs() {
        return this.jzwqs;
    }
    
    public void setJzwqs(String jzwqs) {
        this.jzwqs = jzwqs;
    }
    public String getSyqx() {
        return this.syqx;
    }
    
    public void setSyqx(String syqx) {
        this.syqx = syqx;
    }
    public Date getQsrq() {
        return this.qsrq;
    }
    
    public void setQsrq(Date qsrq) {
        this.qsrq = qsrq;
    }
    public Date getZzrq() {
        return this.zzrq;
    }
    
    public void setZzrq(Date zzrq) {
        this.zzrq = zzrq;
    }
    public String getZddj() {
        return this.zddj;
    }
    
    public void setZddj(String zddj) {
        this.zddj = zddj;
    }
    public BigDecimal getZdjg() {
        return this.zdjg;
    }
    
    public void setZdjg(BigDecimal zdjg) {
        this.zdjg = zdjg;
    }
    public BigDecimal getSbdj() {
        return this.sbdj;
    }
    
    public void setSbdj(BigDecimal sbdj) {
        this.sbdj = sbdj;
    }
    public String getDlrxm() {
        return this.dlrxm;
    }
    
    public void setDlrxm(String dlrxm) {
        this.dlrxm = dlrxm;
    }
    public String getDlrzjlx() {
        return this.dlrzjlx;
    }
    
    public void setDlrzjlx(String dlrzjlx) {
        this.dlrzjlx = dlrzjlx;
    }
    public String getDlrzjh() {
        return this.dlrzjh;
    }
    
    public void setDlrzjh(String dlrzjh) {
        this.dlrzjh = dlrzjh;
    }
    public String getDlrdh() {
        return this.dlrdh;
    }
    
    public void setDlrdh(String dlrdh) {
        this.dlrdh = dlrdh;
    }
    public String getPzwh() {
        return this.pzwh;
    }
    
    public void setPzwh(String pzwh) {
        this.pzwh = pzwh;
    }
    public String getDcbbh() {
        return this.dcbbh;
    }
    
    public void setDcbbh(String dcbbh) {
        this.dcbbh = dcbbh;
    }
    public Blob getZdt() {
        return this.zdt;
    }
    
    public void setZdt(Blob zdt) {
        this.zdt = zdt;
    }
    public Blob getZdct() {
        return this.zdct;
    }
    
    public void setZdct(Blob zdct) {
        this.zdct = zdct;
    }
    public BigDecimal getLifecycle() {
        return this.lifecycle;
    }
    
    public void setLifecycle(BigDecimal lifecycle) {
        this.lifecycle = lifecycle;
    }
    public String getJzlb() {
        return this.jzlb;
    }
    
    public void setJzlb(String jzlb) {
        this.jzlb = jzlb;
    }
    public String getAppid() {
        return this.appid;
    }
    
    public void setAppid(String appid) {
        this.appid = appid;
    }
    public String getYtstybm() {
        return this.ytstybm;
    }
    
    public void setYtstybm(String ytstybm) {
        this.ytstybm = ytstybm;
    }
    public String getQlxz1() {
        return this.qlxz1;
    }
    
    public void setQlxz1(String qlxz1) {
        this.qlxz1 = qlxz1;
    }
    public String getTdzl1() {
        return this.tdzl1;
    }
    
    public void setTdzl1(String tdzl1) {
        this.tdzl1 = tdzl1;
    }
    public String getYzdtybm() {
        return this.yzdtybm;
    }
    
    public void setYzdtybm(String yzdtybm) {
        this.yzdtybm = yzdtybm;
    }
    public BigDecimal getFzmj1() {
        return this.fzmj1;
    }
    
    public void setFzmj1(BigDecimal fzmj1) {
        this.fzmj1 = fzmj1;
    }
    public String getTdzl2() {
        return this.tdzl2;
    }
    
    public void setTdzl2(String tdzl2) {
        this.tdzl2 = tdzl2;
    }
    public String getDcrgzdmzh() {
        return this.dcrgzdmzh;
    }
    
    public void setDcrgzdmzh(String dcrgzdmzh) {
        this.dcrgzdmzh = dcrgzdmzh;
    }
    public String getKzygzdmzh() {
        return this.kzygzdmzh;
    }
    
    public void setKzygzdmzh(String kzygzdmzh) {
        this.kzygzdmzh = kzygzdmzh;
    }
    public String getDcshrgzdmzh() {
        return this.dcshrgzdmzh;
    }
    
    public void setDcshrgzdmzh(String dcshrgzdmzh) {
        this.dcshrgzdmzh = dcshrgzdmzh;
    }
    public String getSharestate() {
        return this.sharestate;
    }
    
    public void setSharestate(String sharestate) {
        this.sharestate = sharestate;
    }
    public String getBgjzxx() {
        return this.bgjzxx;
    }
    
    public void setBgjzxx(String bgjzxx) {
        this.bgjzxx = bgjzxx;
    }
    public String getBgtsxx() {
        return this.bgtsxx;
    }
    
    public void setBgtsxx(String bgtsxx) {
        this.bgtsxx = bgtsxx;
    }
    public String getRghsry() {
        return this.rghsry;
    }
    
    public void setRghsry(String rghsry) {
        this.rghsry = rghsry;
    }
    public Date getRghsrq() {
        return this.rghsrq;
    }
    
    public void setRghsrq(Date rghsrq) {
        this.rghsrq = rghsrq;
    }
    public String getIsrghs() {
        return this.isrghs;
    }
    
    public void setIsrghs(String isrghs) {
        this.isrghs = isrghs;
    }
    public String getDcdw() {
        return this.dcdw;
    }
    
    public void setDcdw(String dcdw) {
        this.dcdw = dcdw;
    }
    public Date getDcshrq2() {
        return this.dcshrq2;
    }
    
    public void setDcshrq2(Date dcshrq2) {
        this.dcshrq2 = dcshrq2;
    }
    public String getDcshr2() {
        return this.dcshr2;
    }
    
    public void setDcshr2(String dcshr2) {
        this.dcshr2 = dcshr2;
    }
    public String getDcshyj2() {
        return this.dcshyj2;
    }
    
    public void setDcshyj2(String dcshyj2) {
        this.dcshyj2 = dcshyj2;
    }
    public String getTdqslyzmcl() {
        return this.tdqslyzmcl;
    }
    
    public void setTdqslyzmcl(String tdqslyzmcl) {
        this.tdqslyzmcl = tdqslyzmcl;
    }
    public BigDecimal getQtyzgytdsyqmj() {
        return this.qtyzgytdsyqmj;
    }
    
    public void setQtyzgytdsyqmj(BigDecimal qtyzgytdsyqmj) {
        this.qtyzgytdsyqmj = qtyzgytdsyqmj;
    }
    public String getKjzb() {
        return this.kjzb;
    }
    
    public void setKjzb(String kjzb) {
        this.kjzb = kjzb;
    }
    public String getWzsm() {
        return this.wzsm;
    }
    
    public void setWzsm(String wzsm) {
        this.wzsm = wzsm;
    }
    public BigDecimal getTxmj() {
        return this.txmj;
    }
    
    public void setTxmj(BigDecimal txmj) {
        this.txmj = txmj;
    }
    public Date getSharetime() {
        return this.sharetime;
    }
    
    public void setSharetime(Date sharetime) {
        this.sharetime = sharetime;
    }
    public String getGhrjl() {
        return this.ghrjl;
    }
    
    public void setGhrjl(String ghrjl) {
        this.ghrjl = ghrjl;
    }


	@Override
	public String getIdName() {
		// TODO Auto-generated method stub
		return "tstybm";
	}


	@Override
	public String getDataVersionName() {
		// TODO Auto-generated method stub
		return null;
	}




}


